### ISSUE TITLE
Airtime, Duty-Cycle and Fair-Use calculation package

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#101]

**Comment by KtorZ** [comment]
There's already one -> https://github.com/TheThingsNetwork/ttn/tree/develop/core/dutycycle

What do you have in mind exactly ? ( we could rename it to have a meaning closer to what it actually does ... )

**Comment by htdvisser** [comment]
At the moment it's only used for gateway duty cycles. We should also use it
on a node-level (for the fair use policy) and in ttnctl (to show how much
airtime you're wasting). Therefore we might want to move the calculation
part to a separate package.

**Comment by htdvisser** [comment]
This has been implemented in the `refactor` branch. See #199 for more info.
