### ISSUE TITLE
Assign AppEUI from the Foundation's MAC block

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#103]
When creating a new application, optionally assign an EUI from The Things Network Foundation's MAC block. Users should not be able to register an application with a specific AppEUI from this block.

The EUI should be generated in the Broker, not in ttnctl.

**Comment by htdvisser** [comment]
@johanstokking: What is our MAC block?

**Comment by johanstokking** [comment]
```
36-bit Base Value (OUI-36)	EUI-48 Address Block
70-B3-D5-7E-D	0-00 through F-FF
```

**Comment by johanstokking** [comment]
We need atomic increment in a distributed way. Since we're going to use Redis anyway (see #100), we can use [INCR](http://redis.io/commands/INCR) here and convert the returned value to a byte array.

**Comment by johanstokking** [comment]
We should implement this in the authentication and authorization server. The Broker trusts the token provider and thus the assigned AppEUIs. Will leave this issue here until it is closed.
