### ISSUE TITLE
Session keys after a join are incorrect

### ISSUE THREAD

**Issue by tftelkamp** [TheThingsNetwork/ttn#110]
After a successful join, the nwkSkey and appSkey on the node differ from those in the backend.

**Comment by htdvisser** [comment]
In the Handler they are calculated here: https://github.com/TheThingsNetwork/ttn/blob/develop/core/components/handler/handler.go#L464-L487

I don't immediately see a difference with the LoRaWAN spec. @KtorZ: do you see any mistake there?

**Comment by htdvisser** [comment]
Same problem in `ttnctl join`: https://github.com/TheThingsNetwork/ttn/blob/develop/ttnctl/cmd/join.go#L145-L159

**Comment by htdvisser** [comment]
Cause of this issue is probably the Endianness of the EUIs/SKeys

**Comment by tftelkamp** [comment]
[LoRaWANandbyteorderingV3_923_2.xlsx](https://github.com/TheThingsNetwork/ttn/files/197128/LoRaWANandbyteorderingV3_923_2.xlsx)

**Comment by htdvisser** [comment]
Fix is merged, will test this with @tftelkamp when he's available.

**Comment by htdvisser** [comment]
Problem is solved.
