### ISSUE TITLE
Migrate Handler to Paho

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#113]
Why:
* The currently used library `github.com/yosssi/gmq` has not seen any code update since 2014
* `gmq` doesn't notice the absence of a CONNACK (when username/password is incorrect), so the Handler will just reconnect.

**Comment by johanstokking** [comment]
Should be Handler. Closes also #58

**Comment by htdvisser** [comment]
TODO: Revert 566ef7c when migrated
