### ISSUE TITLE
Development mode for ABP devices

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#118]
When ABP devices restart, their `FCnt` is reset. This results in messages being rejected.
When a device is configured for development mode, the backend should skip this `FCnt` check. Only question is what to do with downlink `FCnt`

**Comment by johanstokking** [comment]
What should happen with the downlink frame counter is that it should reset when an uplink packet with `FCnt` 0 appears and when the device is in development mode. I don't think that we need to check for uplink frame counter roll over when the device is in development mode.

**Comment by htdvisser** [comment]
Moving this issue to long-term. I think postponing this feature is a good way to encourage developers to use OTAA from the start.
