### ISSUE TITLE
Add port for mqtt downlink

### ISSUE THREAD

**Issue by tftelkamp** [TheThingsNetwork/ttn#127]
Application should be able to specify port for downlink messages, either via the topic or json.

**Comment by KtorZ** [comment]
What do you mean exactly? 
Application being able to connect to the mqtt server on the port they want ?

**Comment by htdvisser** [comment]
Setting the LoRaWAN FPort

**Comment by htdvisser** [comment]
This is relatively easy to implement, but requires a migration of the database in which packets are scheduled. As this database is not easy to migrate, it might be better to wait until we switch from our current binary datastore (Bolt) to Redis.

**Comment by htdvisser** [comment]
This has been implemented in the `refactor` branch. See #199 for more info.
