### ISSUE TITLE
Build of develop fails

### ISSUE THREAD

**Issue by kersing** [TheThingsNetwork/ttn#144]
Build of develop branch fails:
> core/core.go:55: too many arguments in call to cmd.UnmarshalBinary

**Comment by KtorZ** [comment]
Indeed.
Package `core` isn't currently tested, most parts are generated but still, we should add some tests about the part that are written by humans, otherwise typos like this one will sneak in again without being identified neither by Travis nor by Coveralls.

**Comment by htdvisser** [comment]
Nothing wrong with `develop`. Most likely this is a problem with submodules or local dependencies.
You can run the following in a clean machine (`docker run --rm -it golang`) to verify that `develop` builds correctly:

```
git clone --recursive https://github.com/TheThingsNetwork/ttn.git $GOPATH/src/github.com/TheThingsNetwork/ttn
cd $GOPATH/src/github.com/TheThingsNetwork/ttn
make deps
make build
```

**Comment by htdvisser** [comment]
I do agree with @KtorZ that we could add tests to the `core` package.
