### ISSUE TITLE
Events on MQTT

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#159]
Applications should be able to publish more events to MQTT in addition to activations.

- Downlink expired
- Downlink sent

Feel free to add more requests in the discussion.

**Comment by htdvisser** [comment]
Updated list of events:

* Downlink Sent (https://github.com/TheThingsNetwork/node-app-lib/issues/11)
* Downlink ACKed (https://github.com/TheThingsNetwork/ttn/issues/158)
* Payload Function Error (https://github.com/TheThingsNetwork/ttn/issues/254)

All of these are device events, so I suggest to publish these to the `<app-id>/devices/<dev-id>/events` topic. For application events we could add the `<app-id>/events` topic. 

Comments, @johanstokking?

**Comment by johanstokking** [comment]
No comments. Go go go

**Comment by htdvisser** [comment]
Done
