### ISSUE TITLE
Add ability to test payload functions without setting them

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#162]
I think it would make sense to be able to test payload functions before actually committing them to 
the handler.  This makes testing a bit safer and one can do it while the handler is still processing stuff using the old functions (I do not know if this is an existing usecase).

So instead of 
```
write --> set --> test --+
  ^                      |
  |                      |
  +----------------------+

```

We can have
```
write --> test -- (ok) --> set
   ^       |
   |       |
   +-------+

```

We could pass the functions to be tested as separate field in `TestPayloadFunctionsReq`.

Are there reasons not to do this? We could also have both flows at the same time (eg. `TestPayloadFunctions(appEUI, Payload)` and `TestPayloadFunctionsOffline(appEUI, Payload, Functions)`).

I've been looking at the handler code and can make a PR if need be.

**Comment by johanstokking** [comment]
Yes, good idea. I don't see a real use in having both. Let's keep it plain and simple. Make a PR, otherwise assign this issue to me
