### ISSUE TITLE
Application blocked by F-secure

### ISSUE THREAD

**Issue by DIY3D** [TheThingsNetwork/ttn#169]
ttnctl.exe (Version downloaded 19-05-2016) is detected as Suspicious:W32/Malware! 
by F-Secure 16.2

**Comment by htdvisser** [comment]
Please download the latest version of `ttnctl` and let us know if the problem is still there.

I think we should figure out how to sign the exe so that Windows recognises it as a "good" exe. Not sure if this is worth our time, because soon most people will use the web dashboard instead of ttnctl.

**Comment by johanstokking** [comment]
@DIY3D is this still an issue?

**Comment by htdvisser** [comment]
No response, so closing this issue. If anyone encounters this problem again, please reopen.
