### ISSUE TITLE
Can't login after logout

### ISSUE THREAD

**Issue by DIY3D** [TheThingsNetwork/ttn#170]
C:\ttnctl-windows-amd64>ttnctl user
  WARN No login found. Please login with ttnctl user login [e-mail]

C:\ttnctl-windows-amd64>ttnctl user login [my email] 
Password:[my password]
 FATAL Failed to login                          error=User not found

**Comment by htdvisser** [comment]
Thank you for submitting this issue. I'll work with you to figure out what's going wrong here.

Could you please let me know which version of `ttnctl` you are using by submitting the output of `ttnctl version`.

**Comment by johanstokking** [comment]
@DIY3D we haven't heard from you for a while. If you still encounter this issue, please raise a new one, mentioning the output of `ttnctl version`. Also note that your account should be valid by having your e-mail address confirmed. Also try the dashboard; https://staging.thethingsnetwork.org
