### ISSUE TITLE
Support for FSK modulation

### ISSUE THREAD

**Issue by tftelkamp** [TheThingsNetwork/ttn#171]
Packets with FSK modulation should be processed by the back-end.

Example rxpk:

{"rxpk":[{"tmst":2908282292,"time":"2016-05-29T12:41:31.803832Z","chan":9,"rfch":1,"freq":868.800000,"stat":1,"modu":"FSK","datr":50000,"rssi":-43,"size":26,"data":"QAcBAQIAEQABdgjNAB0U3LH+zjs386RiwNA="}]}

For duty cycle calculations:

Tpacket = (lorawan_frame_bytes + 5 + 3 + 1 + 2) * 8/50000

preamble: 5 bytes
syncword: 3 bytes
length: 1 byte
crc: 2 bytes

(taken from LMiC, need to verify)

**Comment by htdvisser** [comment]
Added in cdaaaf37b301098b4019e8b53fd101bd1274b76f
