### ISSUE TITLE
Dashboard: Make AppKey copyable

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#178]
If I need to enter my AppEUI and AppKey into an Android app, it is a lot of effort to type both over by hand, and prone to typo's. It will save a lot of effort if the AppEUI and AppKey can be copied from the dashboard and then pasted wherever they are needed.

Copying of the AppKey from the dashboard is possible when using a computer and mouse, but on a mobile device the AppKey is hidden too quickly to select all and copy the text. 

It will be nice if the dashboard had a button to click to copy the AppKey to the clipboard.

**Comment by romeovs** [comment]
I've pushed a newer version of the dashboard yesterday that has exactly this feature.
It still does not work super-smoothly on safari on iOS because you cannot manipulate the clipboard from safari, but it should work better on android.
