### ISSUE TITLE
Changing ports on ttn.yaml reports some warnings

### ISSUE THREAD

**Issue by edwindvinas** [TheThingsNetwork/ttn#180]
Hi TTN team!

I tried to change the defined ports in the ttn.yaml just to have my own ports assignments. I saw the folllowing errors when I run the daemons:

[Router]
`  WARN HTTP connection lost                     adapter=router-status error=listen tcp: invalid port 80700`
[Broker]
`WARN HTTP connection lost                     adapter=handler-status error=listen tcp: invalid port 80701`
[Handler]
`WARN HTTP connection lost                     adapter=handler-status error=listen tcp: invalid port 80702`

What I did is I just changed the first digits of all ports to say "8" and run the router, broker and handler as is. Is it ok to have these warnings and what can we do to remove this warnings?

I also would like to suggest that on the ttn.yaml configuration, we can indicate which ports need to be retained and which ones can be changed with our own liking?

**Comment by htdvisser** [comment]
A TCP port is only 2 bytes, so the port numbers you're trying to use don't exist.
