### ISSUE TITLE
Hard-coded ports on the code may not match with the ttn.yaml if the ports are re-assigned

### ISSUE THREAD

**Issue by edwindvinas** [TheThingsNetwork/ttn#181]
Related to my raised issue on re-assigning some port numbers, I also noticed in the code that there are hard-coded port literals. In my case, if I change the ports in the ttn.yaml config file, the below code will display the hard-coded values which are not the same as that of ttn.yaml.

```
//broker.go
   brokerCmd.Flags().Int("status-port", 10701, "The port of the status server, use 0 to disable")
   brokerCmd.Flags().Int("uplink-port", 1881, "The port for uplink communication")
   brokerCmd.Flags().Int("downlink-port", 1781, "The port for downlink communication")
//collector.go
   collectorCmd.Flags().Int("port", 1783, "The port to listen for management")
//handler.go
   handlerCmd.Flags().Int("status-port", 10702, "The port of the status server, use 0 to disable")
   handlerCmd.Flags().Int("internal-port", 1882, "The port for communication from other components")
   handlerCmd.Flags().Int("public-port", 1782, "The port for communication with the wild open")
//router.go
   routerCmd.Flags().Int("status-port", 10700, "The port of the status server, use 0 to disable")
   routerCmd.Flags().Int("downlink-port", 1780, "The port for downlink communication")

```

I also want to suggest that if there are ports that we can't re-assign, can we put them in the ttn.yaml so users know that those ports are fixed and can't be changed. And if they want to change, what range of values they can choose from as a replacement to the default ports assigned by TTN? Thanks!

**Comment by htdvisser** [comment]
The values in the code are default values that are used when no configuration is given.
See https://godoc.org/github.com/spf13/pflag#Int
