### ISSUE TITLE
API : GET one device

### ISSUE THREAD

**Issue by honorem** [TheThingsNetwork/ttn#182]
Missing a way to be able to load one and only one device. 
Tried the https://staging.thethingsnetwork.org/api/v1/applications/app_eui/devices/device_eui but throws a 500 Internal Server Error. 

Receive a 400 when sending an invalid device eui "0011223344" :
  `"reason": "invalid device eui: 0011223344"`

So i supposed that the endpoint is actually present but is wrongly sending an error 500

**Comment by johanstokking** [comment]
Working with the v1 API is not supported (yet). Please use the gRPC endpoints you can find in the protos of this repository. See `ttnctl` for example usage.
