### ISSUE TITLE
Have not Recieved Gateway Order

### ISSUE THREAD

**Issue by GeoffreyEmery** [TheThingsNetwork/ttn#185]
Hello I placed a order back in april for my gateway and have emailed your team to find out what the status of the shipment is but have not heard anything.  My Invoice ID is web-259. Can someone let me know what is the status.
Thanks,
   Geoff

**Comment by htdvisser** [comment]
This Github repository is for the development of The Things Network's backend. It is really not the place for asking questions about hardware orders. I suggest you to check out the [contact section of the website](https://thethingsnetwork.org/#contact-section) and send an email or tweet.
