### ISSUE TITLE
fix gateway gps position

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/ttn#187]
Hey!

One of my kerlink GW is inside a building for now and can't get a GPS signal... Is there a way for me to fix its GPS location for now ?

**Comment by htdvisser** [comment]
I guess something like this should work:
```
"fake_gps": true,
"ref_latitude": 10,
"ref_longitude": 10,
"ref_altitude": 10,
```
See also https://github.com/TheThingsNetwork/packet_forwarder/blob/master/poly_pkt_fwd/global_conf.json
