### ISSUE TITLE
Decorate device activation event

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#194]
When device activation using LoRaWAN, add `DevAddr`, `AppSKey` and `NwkSKey` to update monitors live

**Comment by romeovs** [comment]
Also add the `DevEUI`, this is nice to know when listening to activations for all devices of an application.

**Comment by johanstokking** [comment]
The `DevEUI` is part of the topic. Requires some parsing but the topic structure is stable.

**Comment by htdvisser** [comment]
> _topic structure is stable_

This is not entirely accurate, as the topic format will change with the new application structure. Is there already a definition for this, @johanstokking?

**Comment by johanstokking** [comment]
Stable as in it remains `<app identifier>/devices/<device identifier>/[up|down|activations]`. We are indeed changing the app identifier from `AppEUI` to a self-defined but immutable identifier.

If we do that also for devices, then `DevEUI` really becomes LoRaWAN specific and it should be added to the metadata, next to `DevAddr`, `NwkSKey` and `AppSKey`.
