### ISSUE TITLE
TTN network dienies join, should be in coverage

### ISSUE THREAD

**Issue by EvertSchut** [TheThingsNetwork/ttn#198]
See:  TTN no login possible via TheThingsUno (Aruino Leonardo) wich did work in Utrecht meetup 14june2016 #197 

Please really read the problem.

Please Johan, do not close issues until the are solved en do not assume things like I am not in coverage. I spent enough time to investigate this, so please help me.

@johanstokking : I have an external antenna (see problem description), and I visited Utrecht at diffrent days and places (see problem description), where there should be coverage. I can keep on trying, but tried a lot, see initial post for details.
From the behaviour it seems really that somtimes I get a response, wich I presumed te be from the network, since in a cellar it isnt showed in the log.
I should be close enough to a gateway.

@htdvisser : Interesting, essential point, "and does not send a message back when the join is denied", are you sure?
How is explained that
debugPrintLn("Join not accepted: " + response + ". Status: " + ttu.readValue("mac get status"));
gives a parameter value of result that equals "denied"? I only get this when I seem to have coverage... Not in our cellar or with fold up antenna.

Is there some code in the community that gives more information if there is a network present, for example RSSI/BER/Received signal indication?

**Comment by htdvisser** [comment]
Please reopen your issue #197 instead of opening a new issue.
