### ISSUE TITLE
Dashboard: Auto assigned device addresses not in TTN range.

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#202]
I just created a new ABP node under my application with the dashboard and got a device address of: B5D906C4. A few days ago I got F1CD35C1. These addresses do not start with the TTN network ID of 0x26/0x27.

**Comment by htdvisser** [comment]
The staging environment assigns random device addresses. The correct prefix will be used in the production version. This is implemented for the [networkserver](https://github.com/TheThingsNetwork/ttn/blob/refactor/core/networkserver/networkserver.go#L142-L145) in the `refactor` branch.
