### ISSUE TITLE
https://github.com/ttn-zh/ic880a-gateway.git/ not found

### ISSUE THREAD

**Issue by skramer** [TheThingsNetwork/ttn#205]
git clone https://github.com/ttn-zh/ic880a-gateway.git ~/ic880a-gateway
after entering github user/pass

and I get back a message:
fatal: repository git clone https://github.com/ttn-zh/ic880a-gateway.git/ not found
(preventing us from completing our The Things Network LoRa Gateway.. sad... )

The above command comes from:
https://github.com/ttn-zh/ic880a-gateway
section: Clone the installer and start the installation

Can anyone advise what the issue is.. 
Thank you in advance

**Comment by johanstokking** [comment]
This issue is not related to this repository. I see that you already filed the issue at [the right place](https://github.com/ttn-zh/ic880a-gateway/issues/8).

**Comment by skramer** [comment]
thank you kindly .. I will await their reply...
