### ISSUE TITLE
Get Gateway Status from Router

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#209]
The Router should expose the latest status received from a gateway through the [`GatewayStatus` RPC](https://github.com/TheThingsNetwork/ttn/blob/refactor/api/router/router.proto#L98) in the `RouterManager`.

Please add a command to `ttnctl`that retrieves the status of the gateway from the Router and prints it to the command line.

**Comment by b1101** [comment]
closed by #212
