### ISSUE TITLE
Adapt ttnctl to XDG base directory specification

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/ttn#210]
In the current implementation the `ttnctl` config path is hardcoded to be searched for in `$HOME` (in [ttnctl/util/config.go](https://github.com/TheThingsNetwork/ttn/blob/242ec0cb880a9086836a8dda55de622044717ff8/ttnctl/util/config.go#L18-L32) and in [ttnctl/cmd/root.go](https://github.com/TheThingsNetwork/ttn/blob/242ec0cb880a9086836a8dda55de622044717ff8/ttnctl/cmd/root.go#L104-L108)

In Linux environments it make sense to first search in `$XDG_CONFIG_HOME/ttn`, if the variable is set. 
See [XDG base directory specfication](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

In the current implementation it would be necessary to make a special case, as the config file name would have to not be a dotfile(as in `.ttnctl.yaml`)

**Comment by romeovs** [comment]
I will implement this when implementing the account server client token manager.

Having one token in the config is ok-ish, but having multiple tokens will be a pain. Instead, tokens should be stored in `$XDG_CACHE_HOME/ttnctl/tokens` or something similar.

**Comment by htdvisser** [comment]
Also create the config file if it doesn't exist (to avoid warning/error)

**Comment by htdvisser** [comment]
@romeovs implemented this last week.
