### ISSUE TITLE
Enable optional open access to applications

### ISSUE THREAD

**Issue by kgbvax** [TheThingsNetwork/ttn#215]
In the context of   

http://forum.thethingsnetwork.org/t/is-there-a-list-with-public-available-sensors/3002
and
http://forum.thethingsnetwork.org/t/is-ttns-scope-too-small-do-we-need-to-go-beyond-pure-technology/2451

I would like an application owner be able to mark an application as "open".

This should allow public access to the application's data. 
Public presumably means unauthenticated read access to the applications queue.

Motivation:  I think that - being a crowd-source network - TTN should be opinionated about open data, i.e. valuing open data as desirable.
 Right now it is the exact opposite of what I would like it to be - closed is the default. (I acknowledge that in many cases and applications "closed" is the right approach and I am not trying to abandon this)

With this issue, I'd like it at least to be able to be open.
So being open should not be _more difficult than being closed_. 
This is why I believe the at least the open read access should go into TTN „core"

**Comment by johanstokking** [comment]
We would go beyond the scope of a network if we would provide an open registry of applications and open access to the data. It's adding so much more functionality than just allowing access without providing an access key. I do not see this as the scope.

Instead, build an integration with an existing open data platform, for example OpenSensors.io. I'm currently working on the design of the integration architecture, and one of the integrations that we're building will be with OpenSensors.io.

I also [answered on the forum](http://forum.thethingsnetwork.org/t/is-ttns-scope-too-small-do-we-need-to-go-beyond-pure-technology/2451/14?u=johan).
