### ISSUE TITLE
[dashboard] 500 when using a invalid jwt

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/ttn#221]
I noticed that providing a valid, but out-of-scope jwt to the server creates a 500.
It happens about 1 times on 5 when creating applications.
It comes from the fact that sometimes, the dashboard does not force-refresh the jwt

**Comment by cambierr** [comment]
ping @romeovs ?

**Comment by romeovs** [comment]
Thanks for the report!
Can you see the error message by any chance?

**Comment by cambierr** [comment]
here it is: {"reason":"rpc error: code = 2 desc = Invalid operation: rpc error: code = 2 desc = Invalid operation: Unauthorized"}

Btw, the app_eui sent in the json body seems to be ignored and only the one in the url is taken in account.

**Comment by johanstokking** [comment]
The API is for the dashboard and is (currently) not open source, documented and supported. Breaking changes can be deployed any time.

Please use the gRPC services (see https://github.com/TheThingsNetwork/ttn/tree/refactor/api) to interface with the handler. We're working on documentation for the account server API, but that's also still work in progress.

Note that application management is part of the account server. There is no database behind the dashboard API; it only interfaces with the handler, MQTT broker and account server.

**Comment by cambierr** [comment]
I know that (we already use it) but this one is an issue we have sometimes in the dashboard

**Comment by johanstokking** [comment]
Ah, misunderstood, sorry about that. @romeovs will take this. Thanks for reporting.

**Comment by htdvisser** [comment]
Fix deployed in preview dashboard
