### ISSUE TITLE
grpc: Use google.protobuf.Empty instead of api.Ack

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/ttn#230]
The protobuf stdlib provides an [Empty](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty) type, which could be used instead of custom api.Ack type

**Comment by AntoineRondelet** [comment]
Don't forget to do

`go get -v github.com/golang/protobuf/ptypes`
and  `import "github.com/golang/protobuf/ptypes/empty/empty.proto";` in your proto
If you want to use it

**Comment by johanstokking** [comment]
@AntoineRondelet This is builtin no? Looks like it's in the protobuf src

**Comment by htdvisser** [comment]
Done for `ttn@refactor`.

**Comment by htdvisser** [comment]
Also, you should not need to import the `.proto` like @AntoineRondelet commented. If your protobuf installation is correct, these protos should be included in the compiler, so you can just use `import "google/protobuf/empty.proto";`.

**Comment by htdvisser** [comment]
Done
