### ISSUE TITLE
IDs should be lowercase

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#231]
After a discussion at the office we decided that id's (app id, device id, gateway id, ...) should be case insensitive, because having both `Hello-World` and `hello-world` can create a lot of confusion.

Having mixed-case id's that are case insensitive will cause a lot of pain however (you have to store mixed case, but convert to lowercase at every check etc.), so we should force id's to be lowercase.

**Comment by htdvisser** [comment]
Fixed in `refactor` 9955a22f37dcc1fa93ec898c1d892281b1df5c3c

**Comment by AntoineRondelet** [comment]
I already did it in the integration :)

**Comment by htdvisser** [comment]
@johanstokking: is your part also resolved?
