### ISSUE TITLE
Proto files standardization

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/ttn#242]
First, sorry if I'm wrong. I'm not yet super familiar with protobuf!

From what I see in the proto files of the refactor branch, there are a few "special types" like:

`[(gogoproto.customtype) = "github.com/TheThingsNetwork/ttn/core/types.NwkSKey"]`

Am I wrong thinking it breaks compatibility with other languages while compiling files ?

**Comment by htdvisser** [comment]
We import `github.com/gogo/protobuf/gogoproto/gogo.proto` at the top of the proto file. If you do the same in other languages that don't support this option, it will just be ignored.

You can download the proto file [here](https://github.com/gogo/protobuf/blob/master/gogoproto/gogo.proto).
