### ISSUE TITLE
Payload Functions: Pass port as second argument

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#247]
Users will address different types of messages to different ports. In the payload functions I need to know to what port the message was addressed. Currently, I don't have this information.

I'd suggest we add the port as second argument to all 4 functions:

```js
function Decoder(bytes, port) {
  // Decode an uplink message from
  // a Buffer of bytes to an object.

  decodedObj = {};

  if (port === 1) {
    decodedObj.isLightOn = bytes[0];
  }

  return decodedObj;
}
```

Once this is in place here, https://github.com/TheThingsIndustries/dashboard/issues/74 requests for the placeholders to demonstrate usage of the port.

**Comment by htdvisser** [comment]
@johanstokking promised on Slack to also add frame counters to the payload functions (https://thethingsnetwork.slack.com/archives/backend/p1474722721000621). I don't see the added value of adding these counters, especially because they are only relevant for LoRaWAN devices. Could you please elaborate, @johanstokking?

**Comment by johanstokking** [comment]
Yeah we don't need the frame counters indeed, but port is essential.

**Comment by FokkeZB** [comment]
Can we get this port thing rolling? I need it for the Electra demo and Node QS

**Comment by romeovs** [comment]
Closed by #329

**Comment by FokkeZB** [comment]
@romeovs could you create an issue or PR in the docs repo when you make a change that affects users?

https://github.com/TheThingsNetwork/docs/issues/66

**Comment by FokkeZB** [comment]
Shouldn't these be updated as well?

- https://github.com/TheThingsNetwork/ttn/blob/v2-preview/core/handler/convert_fields_test.go#L50
- https://github.com/TheThingsNetwork/ttn/blob/v2-preview/core/handler/dry_run_test.go#L77
