### ISSUE TITLE
Payload Functions: Combine Decoder/Converter/Validator

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#249]
For uplink we have a separate Decoder, Converter and Validator. For downlink we only have an Encoder, although #248 discusses it's perfectly capable of dropping messages.

I'd suggest we drop Converter and Validator. You can do whatever you do in Converter in Decoder and to drop you'd simply return falsy, just like #248 suggests for the Encoder.

This would make it more clear that one function is for down and the other for up, while now you might think the Converter and Validator act on both ways.

**Comment by htdvisser** [comment]
I like it. @johanstokking?

**Comment by johanstokking** [comment]
I like separation of concerns. Also, I like the ability to replace a JavaScript decoder by a Google Protocol Buffers decoder, and keep the converter and validator in place.

**Comment by FokkeZB** [comment]
So why don't we have that separated for downlink as well?

Can we at least group the first 3 so that it is clear that those are for up and encoder for down?

**Comment by johanstokking** [comment]
Good to group. See #248 for the other issue. Summary; de node can be stupid; send analog readings without any conversions or validations to save power. An application doesn't need that.
