### ISSUE TITLE
Add ttnctl to package managers

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#255]
- [x] [Brew](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md)
- [ ] Apt repository
- [ ] Snapcraft

**Comment by dorianamouroux** [comment]
This one can be considered as well http://snapcraft.io/

**Comment by htdvisser** [comment]
Already looked into Homebrew. We need to set up our own Tap for this, which is not quite hard.

**Comment by FokkeZB** [comment]
@dorianamouroux snap craft looks very polished. I'll look into all of them this week.

**Comment by FokkeZB** [comment]
Brew doc was moved: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by FokkeZB** [comment]
I can do https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md but it might make more sense for @htdvisser or someone else who's working on `ttnctl` to do this?

**Comment by FokkeZB** [comment]
@htdvisser could you self assign this issue? I can't, but since you're already on it.

**Comment by joscha** [comment]
references https://github.com/Homebrew/homebrew-core/pull/10918

**Comment by htdvisser** [comment]
Homebrew formula is now done. Currently in a [separate tap](https://github.com/TheThingsNetwork/homebrew-ttn) but we might want to submit a PR for homebrew-core when we're sure the builds are good.

In the meantime, this is what you need:

```
brew tap TheThingsNetwork/ttn
brew install ttnctl
```

**Comment by dbrgn** [comment]
Here's an Arch Linux AUR package: https://aur.archlinux.org/packages/ttnctl-bin/

**Comment by htdvisser** [comment]
Great work! Do you think we can somehow automate updating the package when new versions of ttnctl are released?

**Comment by dbrgn** [comment]
@htdvisser people can flag the package as out-of date on the AUR, then I get a notification. that mechanism usually works well. alternatively an e-mail notification by TTN on new releases for packagers would be nice too.

**Comment by htdvisser** [comment]
Will you be able to maintain the package, otherwise it might be a good idea to publish the package from a TTN account?

You can subscribe to new releases using feed:https://github.com/TheThingsNetwork/ttn/releases.atom

**Comment by dbrgn** [comment]
Sure, you can take over if you want. Do you have someone who is familiar with the PKGBUILD system?

As for the build script itself, it's [pretty simple](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttnctl-bin).

**Comment by htdvisser** [comment]
@rvolosatovs maybe?

**Comment by rvolosatovs** [comment]
I could do that.
Why don't we also set up a `ttnctl-git`, which would build from `master`, such that users always use up-to-date version? I think many arch users would prefer that over binaries and it almost doesn't need maintenance.
On the side note, I also propose adding a package in https://github.com/NixOS/nixpkgs , which I can maintain.

**Comment by dbrgn** [comment]
Sure, a `ttnctl-git` would also be an option.

@rvolosatovs what's your AUR username? I think I can add you as a contributor.

**Comment by htdvisser** [comment]
I can imagine that many people just want to install `ttnctl`, not install Go+all vendors and spend several minutes building from source, but sure, we could add a git/`master` alternative if needed. Should not replace the bin of course

**Comment by rvolosatovs** [comment]
@dbrgn rvolosatovs
@htdvisser I will

**Comment by dbrgn** [comment]
@rvolosatovs added you as maintainer. I think you should be able to publish releases too now.

**Comment by htdvisser** [comment]
We will no longer do this for v2, but it will be done for v3: https://github.com/TheThingsNetwork/homebrew-lorawan-stack
