### ISSUE TITLE
Generate documentation for ttnctl

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#260]
@htdvisser could you use https://github.com/spf13/cobra/blob/master/doc/man_docs.md like you've done before for https://www.thethingsnetwork.org/wiki/Backend/ttnctl/ttnctl and generate a single `README.md` in https://github.com/TheThingsNetwork/ttn/tree/develop/ttnctl?

That way we have the documentation right with the source and I'll pull in the MD to the official docs as discussed at https://github.com/TheThingsNetwork/docs/issues/24

We should probably generate docs as part of pushing new releases to package manages as discussed at https://github.com/TheThingsNetwork/ttn/issues/255 and perhaps include them in the package itself as well?

**Comment by htdvisser** [comment]
Done
