### ISSUE TITLE
"DLsettings" in core/components/handler/handler.go 

### ISSUE THREAD

**Issue by xurt75** [TheThingsNetwork/ttn#262]
Due to the definition of DLSettings in package loranwan are changing, so in this handler.go 
line:755-757
orignal:
DLSettings: lorawan.DLsettings{
			RX1DRoffset: h.Configuration.RX1DROffset,
			RX2DataRate: dataRates[h.Configuration.RX2DataRate],
should be changed to:
DLSettings: lorawan.DLSettings{
			RX2DataRate: dataRates[h.Configuration.RX2DataRate],
			RX1DRoffset: h.Configuration.RX1DROffset,

**Comment by htdvisser** [comment]
We are using a vendored revision of the `brocaar/lorawan` package from before the change, so this is currently not a problem. In the next version of TTN we already use `lorawan.DLSettings`.
