### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#263]
Buggy gateways and attackers can flood the network with messages. We should block components that are sending too frequently,

**Comment by kruisdraad** [comment]
Please keep in mind that you don't do this just based on IP, think about a 3G/4G vodafone deployment which NAT's all to the same address

**Comment by htdvisser** [comment]
This issue should focus on application-level rate limiting, and not on transport or network-level limiting.

**Comment by htdvisser** [comment]
Required for https://github.com/TheThingsNetwork/ttn/issues/270
