### ISSUE TITLE
Read-only mode for v1-staging

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#294]

**Comment by matthijskooijman** [comment]
Isn't this already completed?

**Comment by htdvisser** [comment]
It is enforced by the dashboard, but not by the backend.

**Comment by matthijskooijman** [comment]
Please consider leaving this unchanged, or at least keep allowing registration of new ABP devices. This helps in a seamless migration, see https://www.thethingsnetwork.org/forum/t/seamless-migration-from-staging-to-production-for-otaa-devices/6196

**Comment by htdvisser** [comment]
Ok
