### ISSUE TITLE
Handler adapters

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#30]
Define handler adapters 

    - [ ] Registration
         - [ ] Pull registrations from MQTT bloker
         - [ ] For each registration, send a new request to brokers

    - [ ] App Adapter
         - [ ] Connect to an MQTT broker using root credentials
         - [ ] On `Send` publish the formatted packet to a dedicated topic
         - [ ] Watch to MQTT registration and forward them to `NextRegistration`

**Comment by htdvisser** [comment]
It is not possible to fetch MQTT subscriptions from the broker, so we have to do this differently.

**Comment by KtorZ** [comment]
Done cde75155a20e132991af681a3c6d27de8b6251a3.
