### ISSUE TITLE
Payload Functions: Allow additional functions called from PF

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#305]
We currently wrap the payload functions in `(%s)(payload)` when we execute them:
https://github.com/TheThingsNetwork/ttn/blob/v2-preview/core/handler/convert_fields.go#L70

This makes that if you add another function after your function to do something like:

```js
function Decoder(bytes) {
  return {
    foo: bar(bytes)
  };
}

function foo() {
  return 'alpha';
}
```

You get:

```
Error("(anonymous): Line 7:1 Unexpected token function (and 5 more errors)")
```

We could instead wrap the code in:

```js
%s
Decoder(payload);
```

Or go common-JS-ish with:

```js
exports = {};
%s
exports.Decoder(payload);
```

**Comment by johanstokking** [comment]
Or declare the function in the function

**Comment by FokkeZB** [comment]
That's an option, but not best practice and I rather see people not run into error and then having to guess that's a workaround

**Comment by johanstokking** [comment]
Yes, we can go for the first approach you propose, where we have to teach the users to use `Decoder` as function name, but that's definitely doable.

**Comment by FokkeZB** [comment]
Agree, then it's not a breaking change.

**Comment by romeovs** [comment]
What about this?
```
Decoder = %s
Decoder(payload, port)
```

**Comment by FokkeZB** [comment]
Even better!

**Comment by romeovs** [comment]
On the other hand, that will prohibit things like:
```js
var foo = 10;
function Decoder (payload) { /* ... */ }
```

**Comment by FokkeZB** [comment]
o shoot, true...
