### ISSUE TITLE
Config option to remove colours from output

### ISSUE THREAD

**Issue by kruisdraad** [TheThingsNetwork/ttn#312]
When using a systemd backend for the ttn processes the console logging is 'garbled' due to color tags:

Oct 14 12:17:41 services ttn[2652]: #033[90m DEBUG#033[0m Running Downlink Processors              #033[90mAppEUI#033[0m=70B3D57ED0000D4D #033[90mAppID#033[0m=70b3d57ed0000d4d #033[90mDevEUI#033[0m=00000000527CB036 #033[90mDevID#033[0m=527cb036 #033[90mNumProcessors#033[0m=2

Even though there are logs to file these systemd logs can be used for automated triggers (e.g. restart on specific errors). To make it more readable it should be configurable (or automatically detected?) to disable colors from the output.

**Comment by htdvisser** [comment]
From now on `ttn` and `ttnctl` only output colors when it is known the terminal supports colors. For now the supported terminals are the ones that put `xterm` or `color` in the `TERM` environment variable. If this breaks colors on terminals, we should add them to the list.

In your case, you should just make sure that `TERM` is one that does not support colors :)
