### ISSUE TITLE
maxFCntGap currently hardcoded

### ISSUE THREAD

**Issue by kruisdraad** [TheThingsNetwork/ttn#313]
The maxFCntGap is currently hardcoded to 16384. This gap seems to feel to big. Of course an device might miss a few messages, but i would consider a much lower value like 512, based on the fair use policy that is a lot of time passed between the start and ending of the gap.

Perhaps have this configurable per device, so the device/application owner can decide how strict the gap should be monitored. Also it should be considered to do call 'NotFound' but drop it in a /errors/ MQTT channel warning there is something wrong.

**Comment by htdvisser** [comment]
This number comes from the LoRaWAN specification. We might want to change it later, but for now we'll just follow the spec.
