### ISSUE TITLE
Support events and fields over AMQP

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#325]
This is a **feature request** for **the Backend** (**v2-preview**).

Just like the handler publishes events and fields over MQTT, this should also be done over AMQP so that there is first class AMQP support in the Handler.

**Comment by htdvisser** [comment]
@krital: Thank you for helping us with this! Please have a look at how we did this in MQTT and implement it similarly for AMQP. If you run into any issues, don't hesitate to contact me here or on Slack!

**Comment by Sypheos** [comment]
Done via pull request
