### ISSUE TITLE
I cannot register a LoPy's with lora.mac() as DevEUI

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#334]
To get the MAC address of the LoRa module on a LoPy:

```
telnet <IP>
# login
>>> import binascii
>>> from network import LoRa
>>> lora = LoRa(mode=LoRa.LORAWAN)
>>> binascii.hexlify(lora.mac())
b'70b3d5499585fca7'
```

But when I use `70 B3 D5 49 95 85 FC A7` as DevEUI to register the LoPy I get:

![screen shot 2016-10-27 at 14 13 42](https://cloud.githubusercontent.com/assets/2699409/19766701/9e5a2c0c-9c4f-11e6-9900-86113bac780c.png)

**Comment by FokkeZB** [comment]
The same DevEUI works fine on staging.

**Comment by romeovs** [comment]
This was an issue in the Console, which is now fixed.

**Comment by FokkeZB** [comment]
Confirmed 🎉
