### ISSUE TITLE
Two-step registration at Broker

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#34]
To be better prepared for OTAA, registration at the Broker should be implemented differently:

1. Registration of the application with the Broker: `POST /applications/`  
    data: `appEUI, webhookURL`
2. Registration of personalized devices for the application: `PUT /applications/appEUI/personalized_devices`  
    data: `devAddr, nwkSKey`

**Comment by KtorZ** [comment]
Indeed. 
The protocol has to evolve in a similar way.
