### ISSUE TITLE
mqtt client stops receiving packets after some time

### ISSUE THREAD

**Issue by telmich** [TheThingsNetwork/ttn#340]
This is a **bug report** for **the Backend** **v1-staging**.

Connecting with https://github.com/telmich/lorawan/blob/master/receiver/ttn-receiver.py to 
ttn at some point stops receiving data.

Restarting the script enables data flow instantly.
- My application:
  - App ID: `hackzurichtest`
- My gateway:
  - EUI: `B827EBFFFEC267C7`
- MQTT is connected to: `staging.thethings.network:1883`
- I am using the `paho.mqtt.client` library for the `python` programming language

**Comment by htdvisser** [comment]
_"Restarting the script enables data flow instantly"_ sounds like your client either doesn't automatically reconnect or doesn't automatically re-subscribe to the correct topics after the connection with the MQTT broker is lost. 

In our own MQTT client (in Go) we solved this by explicitly re-subscribing to all topics ( see the [source code](https://github.com/TheThingsNetwork/ttn/blob/v2-preview/mqtt/client.go#L189-L198) ). For you it could be as simple as calling `reconnect()` in an `on_disconnect` callback. 

I hope this helps you solve the problem.
