### ISSUE TITLE
Make "Join not accepted: denied" more specific

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#343]
Related to #314

There are multiple reasons why you could get "Join not accepted: denied".

We need to make this error more specific:

- Was there no gateway within reach?
- Were the keys incorrect?
- Was the downlink with session keys not received in response?

I know some of this is impossible with radio technology, but I predict this will be the top FAQ we'll get after we ship. So anything we can do on either the error returned to (and logged by) the Node **or in the Console** (from the other end) would be welcome.

**Comment by johanstokking** [comment]
Report in the Arduino device library

**Comment by FokkeZB** [comment]
Done: https://github.com/TheThingsNetwork/arduino-device-lib/issues/131
