### ISSUE TITLE
Make validation return informative error instead of true/valse

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#348]
The `api.Validator` interface should be changed to

```go
type Validator interface {
	Validate() error
}
```

The return value of `Validate()` should be `nil` if there is no error, or an `*ErrInvalidArgument` from the package `github.com/TheThingsNetwork/ttn/utils/errors`.

## Example

Let's say we have the following:

```go
type Foo struct {
    Mandatory string
}

type Bar struct {
    Mandatory string
    Sub Foo
}
```

The initial error should be created with `errors.NewErrInvalidArgument`, other errors should be wrapped:

```go
func (b Bar) Validate() error {
    if b.Mandatory == "" {
        return errors.NewErrInvalidArgument("Mandatory", "must not be empty")
    }
    if err := b.Sub.Validate(); err != nil {
        return errors.NewErrInvalidArgument("Sub", err.Error())
    }
    return nil
}
```

**Comment by htdvisser** [comment]
@Niondir will look into this :)

**Comment by Niondir** [comment]
First test returned something like this:
`time="2016-11-09T18:06:16Z" level=warning msg="Error in uplink stream for eui-b827ebfffe44f945: rpc error: code = 3 desc = Invalid Uplink: Protocol not valid: Lorawan not valid: CodingRate not valid: can not be empty"
`

**Comment by htdvisser** [comment]
This looks fine. Maybe in the future, we can change the way the errors are wrapped to make the message more like `Invalid Uplink.Protocol.Lorawan.CodingRate: can not be empty`. For now the current way is fine, let's not add too much in one Pull Request :wink:
