### ISSUE TITLE
Docs: Document Handler AMQP API

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#356]
We need documentation (usage) and an API reference for [AMQP](https://github.com/TheThingsNetwork/ttn/tree/v2-preview/amqp) like we have for [mqtt](https://github.com/TheThingsNetwork/ttn/blob/v2-preview/mqtt/README.md), published on https://www.thethingsnetwork.org/docs/current/mqtt/.

**Comment by htdvisser** [comment]
Will come after https://github.com/TheThingsNetwork/ttn/issues/325

**Comment by krital** [comment]
If the feature is not urgent i might be able to assist, would be a good opportunity to get familiar with the API...

Alex

**Comment by htdvisser** [comment]
Thanks for the offer, @krital! We first want to fully implement the AMQP API (see #325) before we'll document it.

**Comment by krital** [comment]
I understand, my offer stands for both ;-)

**Comment by htdvisser** [comment]
Oh your help is very welcome! I'll put both issues on "in progress" and will try to assign them to you.
