### ISSUE TITLE
Removing nodes and applications from v1 staging

### ISSUE THREAD

**Issue by amkuipers** [TheThingsNetwork/ttn#385]
This is a **{question}** for **{the Console}**.

- Explain what you want to do
I would like to remove the applications on the v1. This is because I do not see the data coming into the v2.

- Explain what steps you took
Go to https://staging.thethingsnetwork.org/applications
Select application
Select settings and try to delete. That did not work.
So, selected every ABP and every OTAA node to delete.
After deleting the nodes tried again to delete the application

- Explain what went wrong or what is missing
Delete application did report error " could not delete application Sodaq Tracker
The url was: https://staging.thethingsnetwork.org/applications/70B3D57ED00019A6

## Environment
v1 staging

- My application:
  - App ID: `{70B3D57ED00019A6}`

**Comment by romeovs** [comment]
You can now properly remove applications from the v1 dashboard.

The fact that you do not receive data in the v2 app is unrelated to it still being in the v1 environment though.
