### ISSUE TITLE
Gateway status in V2, "not activated" 

### ISSUE THREAD

**Issue by DIY3D** [TheThingsNetwork/ttn#391]
This is a **{ request/question/...}** for **{the Backend/}**.

- Explain what you want to do
Migration to V2
- Explain what steps you took:
I deleted my applications and devices. I deleted my old accounts and created I new one forr V2. Next steps: I created a new application and new devices both with new ID's and registered one of my gateway's 
- Explain what went wrong or what is missing
I registered gateway aa555a3676205ac5 but the console displays "not activated", "never seen"
and I don't see data from my nodes. Besides that, if necessary I can't deactivate or delete the gateway's from the V1 enviroment cause I deleted my old user profiles
## Environment

- `ttn version` returns: `Commit={...}`
- `ttnctl version` returns: `Commit={...}`
- My application:
  - App ID: `{70B3D57EF0001B92}`
- My gateway:
  - EUI: aa555a3676205ac5 
   -EUI: 1DEE15A874D24644
   -EUI: B827EBFFFF112CC0
  - Connected to: `router.{eu.}.thethings.network:1700`
- My node:
  - Device ID: `{...}`
  - AppEUI: `{...}`
  - DevEUI: `{...}`
- MQTT is connected to: `{...}.thethings.network:{1883/8883}`
- I am using the `{...}` library for the `{...}` programming language

**Comment by htdvisser** [comment]
This was an issue in the NOC, should be resolved now. For more information about gateway registration, see this page: https://www.thethingsnetwork.org/docs/gateways/registration.html
