### ISSUE TITLE
Component hangs at startup if monitor server down

### ISSUE THREAD

**Issue by jankramer** [TheThingsNetwork/ttn#396]
If a backend component (e.g. broker) has a monitor server in its configuration that is down (e.g. NOC), the component will be stuck in a loop retrying to connect to the monitor during startup. Since the initial connection to the monitors is made synchronously and before the gRPC server is started, the backend component will remain unavailable the entire time.

As far as I understand, monitors are not part of the primary process of the backend. It seems therefore that components should be able to start independently of whether the configured monitor servers are up or down. 

Not really a big issue, but it does introduce some (unnecessary?) brittleness. Any thoughts on this @johanstokking @htdvisser ?

**Comment by johanstokking** [comment]
Yes, components should start in any case, even if monitors are down on start.
