### ISSUE TITLE
handler.mqtt-port and handler.amqp-port are announced but don't exist

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#404]
Ports should be parsed from the `handler.mqtt-address` and `handler.amqp-address` conf instead

- https://github.com/TheThingsNetwork/ttn/blob/develop/cmd/handler.go#L77-L81
- https://github.com/TheThingsNetwork/ttn/blob/develop/cmd/handler.go#L92-L96

**Comment by johanstokking** [comment]
This is done?
