### ISSUE TITLE
Include DevEUI in uplink message

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#406]
This is a **feature request** for **the Backend**.

I'd like to have the DevEUI as part of the uplink message. Upstream components (e.g. IoT platforms) may use the DevEUIs to look up devices and may not be aware of a custom Dev ID. Currently, the advised way is to use the DevEUI as Dev ID, but I'd like to be able to use the Dev ID for human readable reference.

**Comment by htdvisser** [comment]
How would this work when we start supporting non-LoRaWAN devices? Or are we okay with being tied with LoRaWAN like this?

**Comment by johanstokking** [comment]
Put it in the metadata; that's already LoRaWAN specific. Also we're not tied to the term DevEUI there; it's more like a hardware serial
