### ISSUE TITLE
Support for MAC commands

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#41]
For the first sprint, we will merely deal with proprietary MAC commands which basically do nothing. 
The implementation of the LinkCheck, LinkADR, DutyCycle, RXParamSetup, DevStatus, NewChannel and RXTimingSetup will be tackled by the second sprint.

The idea here is to test two commands, one initiated by the device, one initiated by the network in order to ensure the mechanism is working as expected.

**Comment by KtorZ** [comment]
Will do, end of sprint #2

**Comment by htdvisser** [comment]
For now we'll leave it at the `LinkCheck` MAC. Adding more MACs should not be too much work.
