### ISSUE TITLE
Test and Handle OTAA

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#42]
Last step of the the first Sprint, the implementation of the Over-The-Air-Activation process. This will require to strengthen the responsibility of the Broker and its Network Controller. 
Nothing is settled yet about the way a handler is supposed to confirm a registration to an application.

**Comment by cambierr** [comment]
Hi @KtorZ !
I was wondering if anything has been moving in this issue ? We are developing a custom handler for our special use-case, but waiting for the protocol definitions of the join sequence :)

Thanks!

**Comment by KtorZ** [comment]
Hey, I am on it, this week. 

What you can expect for the protocol between broker and handler is [gRPC](http://www.grpc.io/) and [protocol buffers](https://developers.google.com/protocol-buffers/) such that everything is language independent. 

For the OTAA, you can expect the following message:

```proto
message JoinRequest {
    bytes       AppEUI          = 1; // 8-bytes long
    bytes       DevEUI          = 2; // 8-bytes long
    bytes       DevNonce        = 3; // 2-bytes long
    bytes       AppNonce        = 4; // 3-bytes long
}
```

This is not completely settled already however, it will be really close to that. I hope it helps.

**Comment by cambierr** [comment]
Yep, that's exactly what I wanted to know! thank you for fast reaction!
