### ISSUE TITLE
Console, migrate gateway to new packet forwarder

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#424]
This is a feature request for the Console.

- Migrate a gateway from the Semtech protocol to the new packet forwarder.
- Currently you need to delete the gateway and create a new one.
- It would be nicer to just "migrate" the gateway to the new protocol/connector.
- This will allow logging the old EUI and associating it with the new ID. This is good for references purposes if old data needs to be associated with a "new" gateway.

**Comment by romeovs** [comment]
Technicallyy you don't really need to d anything right? The gateway will just work when you install the new packet forwarder.

**Comment by jpmeijers** [comment]
Yes, you are right. I was not aware of that when I created this issue. 

Perhaps close this issue, but put a +1 under "renaming gateway" and "change owner of gateway".
