### ISSUE TITLE
Use the ttn logger instead of apex.log 

### ISSUE THREAD

**Issue by AntoineRondelet** [TheThingsNetwork/ttn#428]
Update all the loggers in the code to use the logger defined in go-utils

**Comment by johanstokking** [comment]
Can you specify where this is not the case?

**Comment by AntoineRondelet** [comment]
In those packages for instance (So almost everywhere)

https://github.com/TheThingsNetwork/ttn/blob/develop/utils/testing/testing.go#L17
https://github.com/TheThingsNetwork/ttn/blob/develop/core/component/component.go#L20
https://github.com/TheThingsNetwork/ttn/blob/develop/cmd/broker.go#L41

For the moment the ttn log is created but never passed as an argument to be used in the core

**Comment by htdvisser** [comment]
Have fun 👍
