### ISSUE TITLE
Use command line flags to set the location of the database

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#43]
It should be possible to configure the path to the `{router,broker,handler}_storage.db` files.

**Comment by htdvisser** [comment]
See also #51

**Comment by KtorZ** [comment]
Now each storage expects a database name as an argument in their constructor. We just need the bridge between the instantiation and the cli flags.

**Comment by htdvisser** [comment]
Starting in branch `issue/43-db-flag`.

**Comment by htdvisser** [comment]
Fixed in 281175e
