### ISSUE TITLE
Make use of the full width of the screen

### ISSUE THREAD

**Issue by jwillemsen** [TheThingsNetwork/ttn#437]
This is a feature request for the Console.

I noticed when looking at the application data on the website there is just a lot of gray space on the left and right which is not used by the website. Especially when also having a payload function not much data can be shown and there is no feature to scroll left/right.

Also look at the buttons for uplink/downlink/activation, not always clear for someone who is color blind like me when they are enabled/disabled.

**Comment by jwillemsen** [comment]
Attached screenshot, I can scroll

**Comment by jwillemsen** [comment]
![screenshot_20170130_131942](https://cloud.githubusercontent.com/assets/47353/22422842/e2e50d4e-e6ee-11e6-8f0f-8754ae127b1d.png)

**Comment by htdvisser** [comment]
- The width of the console was changed some time ago and should be a lot better now.
- The contrast of the filter states was also improved, please reopen if not good enough.

**Comment by htdvisser** [comment]
Executing the following javascript in the browser console will make the UI fill the entire window:
```js
var s = document.createElement("style");
s.appendChild(document.createTextNode("main,main>div,nav>div{max-width: 100% !important}"));
document.head.appendChild(s);
```
