### ISSUE TITLE
Fix the typo on ttnctl applications command; missing "applications" word

### ISSUE THREAD

**Issue by edwindvinas** [TheThingsNetwork/ttn#450]
This is a typo correction for ttnctl applications command (very minor issue)

Impacted entities:
ttn\ttnctl\cmd\applications_register.go
ttnctl\cmd\docs\README.md 

Please correct typo as shown below for the "Long: " description. "ttnctl applications register" should be the correct instead of "ttnctl register".

* FILE: ttn\ttnctl\cmd\applications_register.go
var applicationsRegisterCmd = &cobra.Command{                                        
 Use:   "register",                                                                  
 Short: "Register this application with the handler",                                
 Long:  `ttnctl register can be used to register this application with the handler.`,
>>>> Long:  `ttnctl applications register can be used to register this application with the handler.`,
 Example: `$ ttnctl applications register                                            
  INFO Discovering Handler...                                                        
  INFO Connecting with Handler...                                                    
  INFO Registered application                   AppID=test                           
`,                                                                                   

* FILE: ttnctl\cmd\docs\README.md 
### ttnctl applications register                                          
                                                                          
ttnctl register can be used to register this application with the handler.
>>>> ttnctl applications register can be used to register this application with the handler.                                                                          
**Usage:** `ttnctl applications register`

**Comment by htdvisser** [comment]
Thanks for your report. Feel free to fix this and submit a Pull Request.

**Comment by johanstokking** [comment]
@edwindvinas let me fix that for you

[![Let me fix that for you](http://img.youtube.com/vi/5cNYfOVRrBQ/0.jpg)](http://www.youtube.com/watch?v= 5cNYfOVRrBQ "Fixing a typo")
