### ISSUE TITLE
Ignore "broken" servers

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#46]
When a server is repeatedly unavailable or returns errors, it doesn't make any sense to keep trying to reach it. Therefore we should introduce some exponential backoff for faulty servers.

**Comment by KtorZ** [comment]
Request are ignored for the moment. The non-responding recipients remain as potential recipient though. It could be nice indeed to filter the recipients list dynamically. Not a priority, but still a possible optimization.

**Comment by KtorZ** [comment]
Done 5054e214828e399e545ab646a7d843e2ba5222e8

**Comment by htdvisser** [comment]
Nope. Not done.

**Comment by htdvisser** [comment]
For now The Things Network Foundation hosts the servers, which means that we have control over them. As soon as we open the network up to third parties, we need this functionality.
