### ISSUE TITLE
Gateways http API endpoints

### ISSUE THREAD

**Issue by JuanRamino** [TheThingsNetwork/ttn#471]
This is a feature request for the Backend.

Hi all,

In the ApplicationManager would be nice to have the possibility to CRUD gateways like devices with http API endpoints.

What do you think?

**Comment by johanstokking** [comment]
Yes, this is helpful. Note that this is part of the Account Server, not the Handler where the ApplicationManager is.

It'll be here; https://www.thethingsnetwork.org/docs/network/account/api.html

@romeovs

**Comment by romeovs** [comment]
Updated the docs at https://www.thethingsnetwork.org/docs/network/account/api.html to include gateways.
