### ISSUE TITLE
Console: Cannot set all-zeroes session keys

### ISSUE THREAD

**Issue by matthijskooijman** [TheThingsNetwork/ttn#473]
On console.thethingsnetwork.org, I have an ABP device. Under its settings, I changed the network and app session key to all zeroes. After saving, the key was set to a newly generated key instead of the configured zeroes key.

It makes some sense to forbid an all zeroes key for security, but then this should be noted to the user in an error message, instead of silently changing the key.

**Comment by romeovs** [comment]
The error message now correctly warns the user.

**Comment by matthijskooijman** [comment]
Just tested, looks good to me. Thanks!
