### ISSUE TITLE
Add confirmation to "reset frame counters" to avoid accidental reset of downlink counters

### ISSUE THREAD

**Issue by avbentem** [TheThingsNetwork/ttn#476]
This is a **feature request** for **the Console**.

In Console, clicking/touching "reset frame counters" executes without any "Are you sure" confirmation.

This is a problem when just browsing Console and **accidentally** resetting the downlink counters, as then the device will reject any downlinks with counters lower than the last value it knows.

(This was fine when it only affected the uplink counters, as then the next value as sent by a device will always be accepted, even when the device is not restarted. But since #256 **accidentally** resetting the counters requires a restart of the device.)

**Comment by romeovs** [comment]
Fixed and deployed!
