### ISSUE TITLE
Set gateways "Antenna Placement" does not work

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/ttn#478]
This is a **{bug report}** for **{the TTN Console}**.

- I configure a gateway's "location" and set its "Antenna Placement" to outdoor. Then save the settings.
![antennaplacement-set](https://cloud.githubusercontent.com/assets/16325600/23096828/3e0d9520-f625-11e6-81a7-cbd5f2bb2ed9.png)

- Problem:
  - When I then see the gateways "Antenna Placement" it still shows "(?)"
![antennaplacement-empty](https://cloud.githubusercontent.com/assets/16325600/23096830/4635d668-f625-11e6-8b95-168b83b6e21a.png)

- My gateway:
  - EUI: `{eui-b827ebfffe0ca4a4}`

**Comment by htdvisser** [comment]
I can confirm this issue. Regardless the "antenna placement" setting, the overview does not show the placement.

**Comment by romeovs** [comment]
Fixed and deployed!

**Comment by h0l0gram** [comment]
Confirmed. Its working now! Thanks guys!
