### ISSUE TITLE
Increase time that router schedules downlink to gateway

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#479]
This is a **feature request** for **the Backend**.

Currently, the router schedules downlink messages 100ms before they should be transmitted to the gateway. This is too short for many types of gateway connections (e.g. DSL and cellular) and/or remote locations.

If there's RTT available, we should account for that, but if there isn't, the default should be 1 second. This means that for gateways running older packet forwarders that they will more often overwrite downlink messages, but that is always better than consistently not transmitting downlink at all.

**Comment by htdvisser** [comment]
To avoid double work, this should be implemented together with #420.

**Comment by htdvisser** [comment]
Due to delays in #420, the schedule time was doubled 10 days ago in 1bb19bf818fb4d542b31290076cb888e1b899b98
