### ISSUE TITLE
Text and dropdown widgets in Firefox are mis-aligned

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/ttn#482]
This is a **bug report** for **the Console**.

Using firefox **51.0.1 (32-bit)** on Windows 7. The "text widget" does not show the text in a readable manner. The widget shows a scroll bar and the text is vertical not well aligned.

**Description** is broken (most other text widgets on other settings are broken as well)
**Frequency** Plan is ok

![text-widget-broken](https://cloud.githubusercontent.com/assets/16325600/23126092/735cc2a4-f775-11e6-9999-36d8da318a64.PNG)

Affected by this issue are the followings fields:
- General: Description
- Location: Altitude
- Information: Brand, Model, Antenna

Hint: When I remove css "display:flex" it looks ok then

**Comment by avbentem** [comment]
Same on latest Firefox on a Mac, while all is fine in latest Chrome on the same Mac.

**Comment by romeovs** [comment]
@avbentem @h0l0gram I deployed a fix, can you confirm it works and close the issue accordingly?

**Comment by avbentem** [comment]
Nice, @romeovs, the alignment looks okay now in Firefox 51.0.1 64 bit on a Mac. (And also in my Chrome and Safari.)

However, **I do not see a cursor when the form field is focused in Firefox**. (I guess I didn't see it yesterday either.) This makes it hard to guess that one can type whatever one wants. I can move around in the field, like I can go back a few characters and then type something in the middle of any existing value. So, the text I type appears just fine, but I cannot see where I'm about to type.

Also, any text selection is not visible. I can select a few characters while holding Shift and use the arrow keys, and then hitting Delete will delete only the invisible selection. But I cannot see what I selected.

All is fine in true text fields, such as the gateway's description.

(In Chrome and Safari, I do see the cursor when the field has focus, and I also see selected text.)

**Comment by h0l0gram** [comment]
Thanks @romeovs looks better now on Firefox on Linux (51.0.1 (64-bit)):

- [x] While the vertical alignment is fixed,  
- [ ] there are vertical and horizontal **scroll bars** visible, despite the list empty
- [ ] As stated above **no cursor** is visible in "text-widget".

![no_cursor_lots_of_scrollbars](https://cloud.githubusercontent.com/assets/16325600/23167009/318dfbc6-f843-11e6-928a-bebaa384f7c5.png)


I'll report Firefox on Windows tonight.

**Comment by romeovs** [comment]
Deployed some further fixes, can you confirm these work on Linux?

**Comment by h0l0gram** [comment]
Great work @romeovs! Looks very nice on Firefox on Linux 51.0.1 (64-bit).

- [x] While the vertical alignment is fixed,
- [x] there are vertical and horizontal scroll bars visible, despite the list empty
- [x] As stated above no cursor is visible in "text-widget"

**Comment by avbentem** [comment]
Same good results in Firefox on a Mac.

**Comment by h0l0gram** [comment]
And also looks good on Firefox on Windows 51.0.1 (32-bit).
