### ISSUE TITLE
Frequency plan for AS923 (923-925)

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#491]
This is a proposal for the AS923 channel plan to be used in countries that allow the range 923-925 MHz: Brunei, Cambodia, Hong Kong, Indonesia, Laos, New Zealand, Singapore, Taiwan, Thailand, Vietnam (see [this doc](http://www.gs1.org/docs/epc/uhf_regulations.pdf)). 

This is the upper part of the AS923 band. For the lower part, see #489.

**Default LoRaWAN Channels 1-2**

| Frequency | Bandwidth | Comments |
| -- | -- | -- |
| 923.2 | 125 | _also used for RX2 (SF10BW125)_ |
| 923.4 | 125 | |

**Proposed Channels 3-7 (with `CFList`)**

| Frequency | Bandwidth |
| -- | -- |
| 923.6 | 125 |
| 923.8 | 125 |
| 924.0 | 125 |
| 924.2 | 125 |
| 924.4 | 125 |

**Proposed Channel 8-10 (with MAC command)**

| Frequency | Bandwidth |
| -- | -- |
| 924.6 | 125 |
| 924.5 | 250 |
| 924.8 | 125/FSK |

**Comment by htdvisser** [comment]
There are a couple of countries (Hong Kong, Singapore, Thailand, Vietnam) that can "choose" between the upper (#491) and lower (#489) part of the AS923 band. The join frequencies overlap, so OTAA devices will just receive the correct channel plan based on gateways in the area, but for good coverage, it's best to all use the same frequency plan in a certain region.

Based on geography, I think it would be best to have Singapore together with Malaysia, to have Vietnam and the Northern part of Thailand together with Cambodia and Laos, and the Southern part of Thailand with Malaysia.

**Comment by terrymulijana** [comment]
hi, 
923-926 ( 500mW - 2 Watt ) used for RFID in Indonesia : 
http://www.rfid-indonesia.com/images/Alokasi.Frekwensi.RFID-UHF.EPC.Gen2.Indonesia.jpg

as they've stated beyond those power output will be treated like radio transmitter, can we go with that frequency still ?

thanks

**Comment by htdvisser** [comment]
As far as I know, we're well under 500mW

**Comment by terrymulijana** [comment]
so you're saying I can use RFID frequency license to actually use LoraWAN ?

**Comment by andriyadi** [comment]
Hi @terrymulijana nice to find Indonesian here.
The draft for LoRa band in Indonesia is 919-923MHz, similar to Malaysia. But it's not final.
Btw, I'm not representing the regulator, only happen to have friends in there.

**Comment by daffodilistic** [comment]
Hi,

For Singapore, I'm not sure if this document from the regulator would help, but here it is:
https://www.imda.gov.sg/~/media/imda/files/regulation%20licensing%20and%20consultations/frameworks%20and%20policies/spectrum%20management%20and%20coordination/spectrummgmthb.pdf?la=en

It seems like 923-925MHz should be clear for use?

**Comment by rizkyarlin** [comment]
@terrymulijana 

sir, can you send me the url to that regulation?
