### ISSUE TITLE
Expose context in handler client

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#496]
Currently, there's no way to cancel or set a deadline on a request to the handler, using the handler manager client.

I propose that we add the base `context` the handler will use to the `handler.NewManaderClient` constructor, so the other api functions will not have to change.

@htdvisser If you agree that is the correct way, I can make a PR if you want.

**Comment by htdvisser** [comment]
I think changing the api functions wouldn't be so bad. That way we also follow the Go guidelines: _"Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx"_ (see https://golang.org/pkg/context/)

**Comment by htdvisser** [comment]
Additionally, if you pass a `context.WithDeadline(time.Time)` to `handler.NewManagerClient`, all derived contexts will have the exact same deadline, and all requests will timeout at exactly the same time.

**Comment by romeovs** [comment]
Yes, let's follow the go guidelines.
I'm reopening because this hasn't actually been resolved.

**Comment by htdvisser** [comment]
Won't fix this for v2
