### ISSUE TITLE
Console map default zoom

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#500]
This is a bug report for the Console.

https://console.thethingsnetwork.org/gateways/<your_gateway_id>/settings/location displays a map. Currently the map autozooms to my current location (based on my IP address). This is fine if the gateway's location is not yet set.

If the gateway already has a location set, the map should not zoom to my current location, but rather to the location of the gateway.

**Comment by romeovs** [comment]
This has been resolved.
