### ISSUE TITLE
Console satellite map

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#501]
This is a feature request for the Console, related to https://github.com/TheThingsNetwork/ttn/issues/500.

Problem:
When clicking on the map at https://console.thethingsnetwork.org/gateways/<your_gateway_id>/settings/location, it is difficult to find the exact location because not all buildings are shown on the default map. In Europe the street maps are quite complete, including buildings, but this is not the case in other parts of the world.

Solution:
It would be useful to be able to switch to satellite view. Then one can find the correct building, find the exact location on the building where the gateway is installed, and then clicking to place the marker.

**Comment by romeovs** [comment]
This is implemented!
