### ISSUE TITLE
Support LoRaWAN Class B

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#502]
This is a **feature request** for **the Backend**.

Support Class B for GPS fixed gateways.

**Comment by dotpy3** [comment]
Implementing Class B LoRaWAN in TTN raises a few questions, regarding the gateways, common LoRaWAN implementation on the devices and the back-end:

First, we have to take into consideration that devices, looking for Class B beacons from the gateways, have to listen for a specific period `beacon_research_period` before declaring `BEACON_LOCKED` or `BEACON_NOT_FOUND`. Gateways emit beacons at a `BEACON_PERIOD` frequency.

+ Are `beacon_research_period` and `BEACON_PERIOD` pre-determined depending on the specification and region-specific parameters, or are they determined by the network administrators? If so, what should we take into consideration when setting these parameters? cc @tftelkamp 

Regarding the separation of concerns between gateways and back-end:

+ On the gateways: they play a minor role, mostly emitting beacons - given that it is the back-end that handles the logic of pinging the devices?

+ On the back-end: it should handle most of the logic and scheduling: the task of locating the devices, keeping track of the Class B devices and their periodicity to adapt the scheduling of downlinks, slots management.
