### ISSUE TITLE
Include node location in node data record

### ISSUE THREAD

**Issue by dakoller** [TheThingsNetwork/ttn#506]
This is a feature request for the Backend.

## Explain what you want to do
We  would like to be able to setup an application, where many people can deploy sensors/nodes, whose data show up in the the same application. Our example would be a fine dust or noise sensor, and we want to be able to offer one endpoint where interested parites can get access to the sensor data.

for that reason we would like to be able to set a node location (via API/console - this already works) ...and similar to the gateway location the node location should also show up in the data/mqtt forwarded messages etc.

--> This avoids that people later on need to do lookup with the sensor data in the console, additionally the location of the node might have changed in the meantime.

**Comment by htdvisser** [comment]
This functionality is already implemented and works fine when I test it:

```
ttnctl devices register test
ttnctl devices set test --latitude 12.34 --longitude 34.56
ttnctl uplink <test-devaddr> <test-nwkskey> <test-appskey> <test-fcnt> <test-data>
```

On MQTT:
```
Client mosqsub/24393-Hylkes-Ma received PUBLISH (d0, q0, r0, m0, 'test/devices/test/up', ... (371 bytes))
{"app_id":"test","dev_id":"test","hardware_serial":"008BB99E229AB312","port":1,"counter":1,"payload_raw":"q80=","metadata":{"time":"2017-03-06T09:58:08.438167862Z","frequency":868.1,"modulation":"LORA","data_rate":"SF7BW125","coding_rate":"4/5","gateways":[{"gtw_id":"dev","gtw_trusted":true,"time":"","channel":0,"rssi":-25,"snr":5}],"latitude":12.34,"longitude":34.56}}
```

Similarly, on the console:

<img width="487" alt="screen shot 2017-03-06 at 11 04 21" src="https://cloud.githubusercontent.com/assets/181308/23605357/af42da96-025c-11e7-9dc9-f94a16931416.png">
