### ISSUE TITLE
Gateway antenna gain

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#512]
This is a feature request for the Backend.

When querying a gateway from the account server at
https://account.thethingsnetwork.org/gateways/<gw id>
you get an object containing attributes, under which the `antenna_model`.

A more important attribute would be `antenna_gain`, as this should be use by the gateway to adjust its transmit power to keep to ETSI regulations. It could be deducted from the `antenna_model`, but we can't have a list of all possible antennas and their gains.

I therefore recommend adding an `antenna_gain` field to both the console and the API listed above. Perhaps consider removing `antenna_model`, or use it to automatically fill the `antenna_gain` for known antennas on the console.

Note that `antenna_gain` should have the unit dBi, which means the minimum value would most likely be 2.15dBi (2.15dBi=0dBd). Perhaps warn the user when the antenna gain is not filled in, and if the user entered a value below 2.15.

**Comment by htdvisser** [comment]
If we do this, we can also inject it into the gateway config file :)
