### ISSUE TITLE
Rename region to frequencyPlan in gateway status proto

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#520]
This is a **change request** for **the Backend**.

https://github.com/TheThingsNetwork/ttn/blob/develop/api/gateway/gateway.proto#L82

Should be `frequencyPlan`

**Comment by htdvisser** [comment]
Note: This will be a breaking API change for the JSON API (`status.region`) and Go API (`status.Region`). Binary representations of the protos will remain unchanged.

Possibly affected (apart from this repo):

- gateway-connector-bridge ( @htdvisser )
- noc ( @rvolosatovs )
- value-exchange ( @jankramer )
- console ( @romeovs )

**Comment by jankramer** [comment]
Not used by VX, so no issues there.

**Comment by romeovs** [comment]
Console uses protos so it should be good.

**Comment by rvolosatovs** [comment]
Not used in NOC

**Comment by johanstokking** [comment]
It will break the `ttn-gateway-connector` when protos are regenerated, but that's a really minor change for users
