### ISSUE TITLE
Simulated Uplink button not functioning after correcting a false hex-value

### ISSUE THREAD

**Issue by vannut** [TheThingsNetwork/ttn#531]
This is a **bug report** for **the Console**.

I'm trying to sent a simulated uplink from a device to test a mqtt-listener in my own application. 
Steps:
- Go to application > device > choose a device
- Fill in a *false* hex-value eg `EE F`
- Hit Send-button
- Error message appears, telling me the value is wrong. 
- Change the value to `EE FF`
- Hit send again

Nothing happens. I would think the message is newly validated and sent.

## Environment
https://console.thethingsnetwork.org

**Comment by romeovs** [comment]
This is fixed @vannut  can you confirm this and close the issue accordingly?

**Comment by vannut** [comment]
Jups. Confirmed 👍
