### ISSUE TITLE
Console: gw location change, drops privacy settings

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/ttn#535]
This is a **bug report** for **the Console**.

- When I set the location of the gateway, the 3 privacy settings (Privacy > Status,Location,Owner) are all  dropped/set to "not public". I would **not** expect the privacy sections to be changed, when I edit another section "location".

**Comment by romeovs** [comment]
That should not happen indeed. Looking into it!

**Comment by romeovs** [comment]
Fixed it, please confirm and close the issue.

**Comment by h0l0gram** [comment]
Tested and it works. thanks a lot night shifter @romeovs!
😀
