### ISSUE TITLE
Make docker image fail

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#554]
Execuse me , should my running linux system be a 64 bit and not 32 bit cause this is what is written in the end of the Makefile : 
**docker: GOOS=linux
docker: GOARCH=amd64
docker: $(RELEASE_DIR)/ttn-linux-amd64
	docker build -t thethingsnetwork/ttn -f Dockerfile .**

And this is the failure of the command make docker : 
administrator@debian:~/work/src/github.com/TheThingsNetwork/ttn$ make docker
docker build -t thethingsnetwork/ttn -f Dockerfile .
Sending build context to Docker daemon 71.14 MB
Sending build context to Docker daemon 
Step 0 : FROM alpine
 ---> 65312f45ea0c
Step 1 : RUN apk --update --no-cache add ca-certificates
 ---> Running in 3fd1bb085987
**exec format error
INFO[0003] [8] System error: exec format error          
Makefile:175: recipe for target 'docker' failed
make: *** [docker] Error 1**

I thought it may be related to the version of my debian system (32 bit), i don't know exactly, can you help me !!!!!!!!

**Comment by htdvisser** [comment]
TTN does not support 32 bit Docker. Sorry.

If you want to run TTN on a 32 bit machine, you'll have to use the binaries directly (can be built from the latest `master` branch)
