### ISSUE TITLE
Extract Data from theThingsNetwork or Lora Gateway and transfer to my own Server

### ISSUE THREAD

**Issue by zaheentheawesome** [TheThingsNetwork/ttn#555]
Can I have the method of extracting data from TheThingsNetwork and transfer them to my own server?
Is it possible that I don't use the TTN and send data to my server directly from LoraWan Gateway?

Kindly help

Zaheen
7042747307

**Comment by johanstokking** [comment]
Yes, use [MQTT](https://www.thethingsnetwork.org/docs/applications/mqtt/) or the [HTTP integration](https://www.thethingsnetwork.org/docs/applications/http/).

You can also run the TTN open source components on your own server, see https://www.thethingsnetwork.org/article/setting-up-a-private-routing-environment

Finally, you can also implement your own LoRa(WAN) network server, starting here: https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT

**Comment by zaheentheawesome** [comment]
Thanks for the information
