### ISSUE TITLE
make dev-deps problem

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#557]
administrator@ubuntu:~/work/src/github.com/TheThingsNetwork/ttn$ make dev-deps
govendor sync -v
bash: govendor: command not found
make: *** [deps] Error 127

**# GO version** :  go version go1.8.1 linux/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/administrator/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build658598883=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by Sypheos** [comment]
Hi there !

Can you provide more info ? Look like it come from the go installation.

**Comment by rabiihlioui** [comment]
problem solved by Add govendor to deps #521

**Comment by Sypheos** [comment]
Did you installed govendor ?

go get -u github.com/kardianos/govendor

**Comment by rabiihlioui** [comment]
i changed i line in makefile, it didn't know the whole path of the command govendor

**Comment by Sypheos** [comment]
Don't forget to set $GOBIN and append it to your $PATH variable.

https://golang.org/doc/code.html#GOPATH
