### ISSUE TITLE
failed to start all backend services

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#559]
administrator@ubuntu:~/work/bin$ ./forego start
ERROR: open Procfile: no such file or directory

**Comment by gomezjdaniel** [comment]
`forego start` not `./forego start`

**Comment by gomezjdaniel** [comment]
Go to the directory where you cloned this repository, then type `forego start`

**Comment by rabiihlioui** [comment]
i added it in the PATH variable

**Comment by rabiihlioui** [comment]
i tried that but i still have the same error

**Comment by rabiihlioui** [comment]
problem solved,how do i delete an issue cause sincerely it was a silly problem

**Comment by Sypheos** [comment]
Close issue. Their is actually no way to delete issues for now.
