### ISSUE TITLE
The Things Network IHM

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#561]
Excuse me, can i use my own template IHM on TheThingsNetwork backend ?

**Comment by htdvisser** [comment]
First of all, please follow the issue template. It's there for a reason.

Could you be a little more specific with what you mean?

**Comment by rabiihlioui** [comment]
i want to use my own dashboard (my own console) just like in the site of the things network  can i implement it on the backend .

**Comment by johanstokking** [comment]
Yes, see the [docs](https://www.thethingsnetwork.org/docs) for the APIs. The Console does little different than calling the API of the Handler and Account Server. You'd also need an Account Server implementation that suits your needs.
