### ISSUE TITLE
Failed to create client transport

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#562]
After running forego start i get a failure saying that the resetTransport failed to create client transport.

hdl.1  |  DEBUG grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:1900: getsockopt: connection refused"; Reconnecting to {localhost:1900 <nil>}
brk.1  |  DEBUG grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:1900: getsockopt: connection refused"; Reconnecting to {localhost:1900 <nil>}
rtr.1  |  DEBUG grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:1900: getsockopt: connection refused"; Reconnecting to {localhost:1900 <nil>}
hdl.1  |  DEBUG grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:1900: getsockopt: connection refused"; Reconnecting to {localhost:1900 <nil>}
ns.1   |   INFO ttn: Got public keys for token validation

**Comment by htdvisser** [comment]
The discovery component (dsc) runs on port 1900. While the discovery server is still starting, you might see these messages (note that they're just DEBUG messages). If this keeps happening, check why the discovery component is not starting.

**Comment by htdvisser** [comment]
closing for now

**Comment by htdvisser** [comment]
Also, please follow the issue template. It's there for a reason.
