### ISSUE TITLE
Changing device description of an OTAA device, system returns to pre-join state for device

### ISSUE THREAD

**Issue by forrestfiller** [TheThingsNetwork/ttn#563]
This is a **bug report** for **the Console**

- When changing the device description of an OTAA device, the system returns to the pre-join state for that OTAA device. As a result:
  - The device's `DevAddr` and `App Session keys` are no longer valid, thus the device must be manually instructed to re-join.

This was discovered by @terrillmoore and I tonight at the [Heat Seek](http://heatseek.org/) meetup as we work to set them up to pilot with TTN.

Thanks!

Forrest

Please tag [Terry Moore](https://github.com/terrillmoore) in all correspondence.

**Comment by htdvisser** [comment]
Confirmed

![issue563 mov](https://cloud.githubusercontent.com/assets/181308/25220175/41f67d08-25b1-11e7-9603-d578ea455282.gif)

**Comment by htdvisser** [comment]
Fixed in console repository. Will be deployed to production soon.

**Comment by htdvisser** [comment]
Deployed to production. Fix confirmed.

![issue563fixed mov](https://cloud.githubusercontent.com/assets/181308/25230830/c562146c-25d5-11e7-81d9-1b842770b40e.gif)

**Comment by terrillmoore** [comment]
Thanks for the prompt response, all! Much appreciated!

**Comment by forrestfiller** [comment]
Yes, thanks again, appreciate it! :+1:
