### ISSUE TITLE
Current TTN USERNAME does not allow for any valid email address

### ISSUE THREAD

**Issue by OwenBrotherwood** [TheThingsNetwork/ttn#564]
It is often desirable to use one's email address as a USERNAME.
The current check on valid USERNAME does not allow this.
Example:
name.notethedot@domain.tl
ie the . (full stop/dot) is not allowed

![image](https://cloud.githubusercontent.com/assets/866122/25220450/22a16264-25b2-11e7-8433-b824518c04c1.png)

**Comment by johanstokking** [comment]
We need a username for public display (e.g. on the forum, community pages, gateway info). E-mail addresses are kept private, unless you decide otherwise.

The reason why you can't use e-mail address characters for the username, is that we want the username to be used in urls as well.

**Comment by OwenBrotherwood** [comment]
Probably a good place to state email not advised ...

```
USERNAME
This will be your username — pick a good one because you will not be able to change it.
```
