### ISSUE TITLE
Some issue in ADR algorithm implementation

### ISSUE THREAD

**Issue by mariuszslabicki** [TheThingsNetwork/ttn#568]
This is a **probably bug** report for ADR algorithm. 

I want to evaluate ADR in simulating environment.

In the last loop (lines: 64-66 in adr.go file) there is mechanism which increase TxPower every nStep:
```
	for nStep < 0 && txPower < f.ADR.MaxTXPower {
		txPower += 3
	}
```

But this nStep variable is not incremented in the loop. So the final output is that the txPower will be set for f.ADR.MinTXPower, because loop won't stop before that.

Link to file:
https://github.com/TheThingsNetwork/ttn/blob/develop/core/band/adr.go
From commit: bbde582

**Comment by htdvisser** [comment]
Thanks for your report. This indeed seems to be wrong. Do you want to submit a pull request with a fix? Otherwise I'll fix this next week.

**Comment by mariuszslabicki** [comment]
Done. It was a simple change.

**Comment by htdvisser** [comment]
I know 😉 but a simple change that just made you a contributor to this awesome project 👍

**Comment by mariuszslabicki** [comment]
Thank you, I am glad if I helped.
