### ISSUE TITLE
Re-adding deleted application returns error

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#573]
I want to delete an application it says it doesn't exist anymore and when i want to add it with the same AppID it says that this app exist :

```
administrator@ubuntu:~$ ttnctl applications delete omniacom3
Are you sure you want to delete application omniacom3?
yes
 FATAL Could not delete application             error=Application with id omniacom3 does not exist
administrator@ubuntu:~$ ttnctl applications add omniacom3 "testapplication"
 FATAL Could not add application                error=An app with the application id omniacom3 already exists
```

**Comment by Sypheos** [comment]
Application are actually not deleted. When you 'delete' they are hidden and not accessible anymore.
It's confusing and we are working on it.

For the moment I would suggest you stick with the App you have and only remove/add devices inside.

**Comment by htdvisser** [comment]
@romeovs: 

- Please return OK when deleting an already deleted resource
- Please allow re-registering an application if the owner is the same

**Comment by htdvisser** [comment]
@rabiihlioui:

Please follow the issue template when creating issues. That really helps us when we address them.

**Comment by romeovs** [comment]
This is actually a very subtle issue and resolving it should be done with great care. 

Going at it I came up with a couple of not-so-trivial questions:

1. Should all collaborators be able to restore an app? If so what rights should they have? `delete` presumably. But then we can't remove the app collaborators from the app on deletion. What if someone restores the app without our consent? This might introduce a lot of unexpected behavior for user (who generally would expect deleting an app removes all it's state, mainly the collaborators).
2. Note that an app does not know a concept of *owner* it just has a number of collaborators. We could assume it's the first user that created the app, but that's fragile and introduces a lot of support requests (like the gateway already has):
>  please change the owner of app `foo` to my colleague
Unless we also create an api for this (maybe just a right `restore` might work here).
3. Deleting an app removes it from all future jwt access tokens users create (that's the whole point), but how to authenticate for restoring an app then? You can never obtain authentication for a deleted app. We would need to build a custom authentication step for this, further complicating the account server api.

cc @htdvisser @johanstokking

**Comment by johanstokking** [comment]
Let's not make it too complicated by introducing an undelete feature. That is asking for trouble as you illustrated. Also constraining only old collaborators with the `delete` right to undelete the application is not intuitive.

I think there are two options:
1. There's no such thing as deleting

**Comment by htdvisser** [comment]
Let's just call it "Archive" instead of delete and be done with it

**Comment by ama9910** [comment]
The issue I observed is that when deleting an application with ttnctl, the devices remained active. There is now no way to delete those devices using ttnctl, without first selecting the now deleted application - which can't be done.

Proposed option 1 above would allow the application to be unarchived and the devices deleted.

Another alternative might be for `ttnctl applications delete` also delete the devices as @htdvisser suggested in #private-backend.

**Comment by johanstokking** [comment]
Yes, these are two separate things. We will take unarchiving into account for the next version of the account server. When an application is deleted, it should be unregistered from the handler, which invokes deleting devices.
