### ISSUE TITLE
Handler not discovered in local server

### ISSUE THREAD

**Issue by rabiihlioui** [TheThingsNetwork/ttn#577]
root@debian:/home/administrator/ttn# ./ttnctl applications register
  INFO Discovering Handler...                   Handler=mynetwork-handler
  INFO Connecting with Handler...               Handler=localhost:1904
 FATAL Could not register application           error=Could not register application on Handler: Application already exists source=Wrap: /go/src/github.com/TheThingsNetwork/ttn/utils/errors/errors.go:217

**Comment by htdvisser** [comment]
@rabiihlioui: Please follow the issue template when creating issues.

**Comment by rabiihlioui** [comment]
didn't understand you

**Comment by htdvisser** [comment]
When creating issues, we require everyone to follow the issue format, so that we can reproduce it:

<img width="713" alt="screen shot 2017-04-26 at 11 53 42" src="https://cloud.githubusercontent.com/assets/181308/25428771/0ee3c4c8-2a77-11e7-871d-ccb7a61719fa.png">

**Comment by rabiihlioui** [comment]
ok i'm sorry.
