### ISSUE TITLE
Gateway model "not specified" in community map

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/ttn#583]
This is a **{bug report}** for **{the community website}**.

Despite I set a "model" for my gateway eui-b827ebfffe0ca4a4 in the console, in the community map, the tooltip entry for model says "Not specified".
Brand and antenna are correct.

I quickly checked other gateways, none of them show a model in the community map tooltip. I guess the model entry is not read from the gateway meta data at all.

**Comment by johanstokking** [comment]
Confirmed

**Comment by gomezjdaniel** [comment]
Fixed https://www.thethingsnetwork.org/map?gateway=487

**Comment by h0l0gram** [comment]
Thanks. Also works in community page now!
