### ISSUE TITLE
Add log fields to Handler's message brokers publish

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#589]
This is a **feature request** for **the backend**

Currently, the Handler only publishes the protocol for which a message has been published, lacking any context. When something goes wrong, we only see this in the logs:

```
WARN Could not publish Uplink                 Protocol=AMQP error=Unable to marshal the message payload
```

We need more context here

**Comment by htdvisser** [comment]
I was already doing this
