### ISSUE TITLE
Handler in-memory processed nodes

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#59]
The handler maintains an in-memory map of last processed node (It associates a frame counter to a devEUI + appEUI). 
This is required to make sure it doesn't handle twice an already processed packet (The handler buffers for a while packets, but then, process all received packets associated to a same FCnt and should just ignore any new one). 

Even though it only keeps in memory the last frame counter registered, there is likely to be a memory-leak here: the map grows indefinitely as long as the handler is running. We should define a clever data structure that could flush entries automatically after a while.

**Comment by htdvisser** [comment]
Looks like this is taken care of
