### ISSUE TITLE
Cayenne LPP -- wrong conversion of LPP_DATA_TYPE 104 field

### ISSUE THREAD

**Issue by hirnidrin** [TheThingsNetwork/ttn#597]
This is a **bug report** for **the console.**

> What do you want to do? 

I have a node that reports humidity in LPP_DATA_TYPE 104 (0x68) format: 1 byte unsigned integer, 0.5% step per integer unit, [as specified in the Cayenne doc](https://mydevices.com/cayenne/docs/#lora-cayenne-low-power-payload-data-types)

> What steps did you take? 

I activated the Cayenne LPP payload format, setup a Cayenne integration, setup the node in Cayenne... all ok so far, humitity level is displayed correctly.

> What went wrong or what is missing?

When I check the incoming raw message in the Data tab, there is a negative value displayed for the humidity field created by the Cayenne payload conversion:
`{
  "analog_in_3": 0.99,
  "relative_humidity_2": -55.5,
  "temperature_1": 8.8
}`
The raw incoming byte value is 0x91 in this example, calculates to 145 decimal -> should result in 72.5 % relative humidity.
When raw incoming byte is in the 0x7x range (below 128 decimal, MSB not set), the value is converted correctly in the TTN console.

The bug seems to be that the Cayenne LPP payload conversion code used for console display **treats the unsigned integer as a signed integer**, converting everything above 0x7F (everything above 63.5% RH) to a negative integer, and so to a negative RH value.

**Comment by johanstokking** [comment]
Thanks for reporting, I filed an issue in the concerning repository, see reference.
