### ISSUE TITLE
Easy Handler manager client connection

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#601]
This is a **feature request** for **the backend**.

Currently it requires a lot of work to connect to a Handler manager client; dial discovery, lookup announcement, get token with the right scope exchanged by an access token, prepare context with that token and dial the manager client.

Imo it should be as easy as the Go MQTT client; only requiring the app ID, access key and handler ID, optionally providing a discovery address and CA path. It should be part of the `api` package to be reusable by applications. It's basically a wrapper around what we have, although we can consider passing the access key to the Handler as the Handler can exchange it for a token as well.

**Comment by htdvisser** [comment]
See https://github.com/TheThingsNetwork/go-app-sdk
