### ISSUE TITLE
Not able to program ThingsNode under Linux

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#606]
This is a bug report for Arduino device/ThingsNode/Documentation.

> What do you want to do?

Program the device.

> What steps did you take?

Arduino IDE, Sparkfun Micro, ATMega 32u4 8MHz, program.

> What went wrong or what is missing?

It did not program.

> What kind of OS/Browser/Gateway are you using? Which version?

Linux Mint, Ubuntu, ...

> Can you fix this yourself and submit a pull request?

Follow the steps here, especially the part about ModemManager:
http://www.arduino.org/learning/getting-started/arduino-ide-on-linux-based-os

This does not always seem to help. 

![image](https://cloud.githubusercontent.com/assets/948278/26149930/8e3e7110-3afc-11e7-982e-8f85c1d08f4e.png)

**Comment by johanstokking** [comment]
Seems like a general serial port on Linux issue, might be in combination with Arduino IDE but might be unrelated as well. Check if the user is in the `dialout` group, which would be a permission issue, although the error message indicates that the port is not found at all.

**Comment by jpmeijers** [comment]
The user was in the dialout group from the start. After uninstalling ModemManager it worked once, then not. After a restart of the computer it works again. Seems to keep on working.

**Comment by johanstokking** [comment]
If it's specific to the library, which I think it's not, then file the issue in the concerning repository; https://github.com/TheThingsNetwork/arduino-node-lib for example

**Comment by jpmeijers** [comment]
No I'm going to open this issue again. The fix is to update the documentation. It's not something we can solve in code.

**Comment by johanstokking** [comment]
Replaced by https://github.com/TheThingsNetwork/ttn/issues/606; let's keep this repository clean for routing and issues for non-open source components
