### ISSUE TITLE
Things Network account verification email goes to spam

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#607]
This is a bug report for the console/account server.

Not sure if we can do anything about this, but worthwhile to know about it. 

Someone reported to us at TNW that the verification email went to spam.

**Comment by romeovs** [comment]
It's an issue with send grid. I've contacted their support a few weeks ago but have gotten no reply as of yet. Will escalate. We're paying for send grid so they should come back to us!

**Comment by romeovs** [comment]
Got the spam score down to 3.5, should not end up in spam anymore.
