### ISSUE TITLE
Add Gateway-Router mapping to Discovery

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#615]
This is a **feature request** for **the backend**.

> What do you want to do?

Add Class C support (issue #440)

> What is missing?

Although we know on which gateway the class C downlink needs to be transmitted, the Broker doesn't know to which Router the gateway is connected.

> What do you need?

Gateways should announce themselves to the Discovery server. If this is not possible, Bridges/Routers should do this for the gateway.

**Comment by cambierr** [comment]
WIP at https://github.com/cambierr/ttn/tree/feature-615-router-gateway-mapping-in-discovery
