### ISSUE TITLE
Cannot delete community blog post

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/ttn#616]
This is a **bug report/feature request** for **the community website**.

I created a post blog in the community page which I later want to delete.
Unfortunately, I can't find a delete button on the post's page or elsewhere to delete the blog post. 
![no_delete_button](https://cloud.githubusercontent.com/assets/16325600/26713649/f9b41e0e-476d-11e7-805f-7aab72984f38.png)

I would expect a delete button just left of the "publish" button in the post page. 
(similar to the delete features in the console)

**Comment by gomezjdaniel** [comment]
It can be deleted from the dashboard page (/dashboard) which only core members have access

**Comment by h0l0gram** [comment]
Correct. GonzaloCasas pointed that out too.
But I think the author of a post should be able to delete his own posts, no matter what role he/she has within the community.
