### ISSUE TITLE
Add LoraWAN MAC info to MQTT events

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#620]
This is a **feature request** for **the backend**.

> What do you want to do?

I would like to have a disassembly of MAC commands too. It helps with debugging and gaining knowledge from live traffic.
It will complete the data monitoring and analysis.

> What went wrong or what is missing?

The MAC info.

**Comment by dbrgn** [comment]
This would be useful! It would also be awesome if MAC commands could be sent directly from the web UI.

**Comment by htdvisser** [comment]
Information about MAC handling is published as events in v3.

We do not have support (and it is unlikely we will in the future) for triggering MAC commands from the application layer.
