### ISSUE TITLE
Can not edit wiki

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#624]
This is a bug report for the wiki.

> What do you want to do?

Edit an article.

> What steps did you take?

Go to the article, and click on edit at the top right. Add modifications and click on save.

> What went wrong or what is missing?

I am redirected to a "create article" page.

> Do you have Screenshots?

![2017-06-09-081356_982x985_scrot](https://user-images.githubusercontent.com/948278/26966926-a9ca7b8a-4ceb-11e7-825e-c764e526e5b8.png)

![2017-06-09-081228_982x985_scrot](https://user-images.githubusercontent.com/948278/26966933-ae5690bc-4ceb-11e7-983c-66915cba0a6e.png)

> What kind of OS/Browser/Gateway are you using? Which version?

Chromium Version 56.0.2924.84 Built on Ubuntu 14.04, running on Raspbian 8.0

> Can you fix this yourself and submit a pull request?

No. But a workaround is to edit the article on github, but you need special permissions for that.

**Comment by dorianamouroux** [comment]
We can now edit on the website

**Comment by johanstokking** [comment]
So this is resolved?
