### ISSUE TITLE
Add feature to overrule gateway GPS via console

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/ttn#625]
Many gateways are not correctly positioned due to hard-coded GPS in the gateways, or outdated locations when a gateway is moved indoor. 
_31 GWs are on 0;0 island, 16 on 10;20, several are floating in the ocean._

I propose a checkbox in the console stating:
- [ ] Disable gateway GPS

@romeovs @htdvisser

**Comment by jpmeijers** [comment]
Also see https://github.com/TheThingsNetwork/ttn/issues/543

**Comment by htdvisser** [comment]
Won't do this. The gateway is the primary owner of its location information. The location from the console is a fallback.
