### ISSUE TITLE
Add OAuth2 clients management to ttnctl

### ISSUE THREAD

**Issue by dotpy3** [TheThingsNetwork/ttn#631]
Now that there are endpoints on the account server to manage OAuth2 clients, it would probably be useful to be able to manage those clients through `ttnctl` (add, consult, modify, delete them).

**Comment by romeovs** [comment]
I don't think we need this. The client management can be done from the console and involves emails and TTN staff acceptance. There's always going to be human intervention so we don't need ttnctl to this programmatically.

(cc @johanstokking).
