### ISSUE TITLE
Label console gateway location as fallback

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#632]
This is a feature request for the console.

> What do you want to do?

It is unclear why I have to set the location of my gateway on the console.

> What went wrong or what is missing?

A better description what the location is used for.

See https://github.com/TheThingsNetwork/ttn/issues/625#issuecomment-309514376

According to @htdvisser the location set on the console is a **fallback** location for the gateway in the case that the gateway does not report its own location. Perhaps the console should say more explicitly that the  location you set there is a secondary/fallback location, and that the location provided by the gateway takes precedence.

Currently I get many questions from people who are confused where the maps get their gateway location from. Especially if they set their gateway location on the console, but the gateway does not move to the new location on the maps. A simple line on the console calling the location set there a "fallback location" should suffice.

**Comment by htdvisser** [comment]
Won't do this for v2. In v3 we'll be more clear about the location source and priority of different sources
