### ISSUE TITLE
Support harmonized SRD bands in EU 863-867 frequency plan

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#636]
This is a **feature request** for **the backend**.

The duty cycles should be:

- 863-865: 0,1%
- 865-868: 1%

**Comment by BWhitten** [comment]
Band L is 865-868: 1%

**Comment by johanstokking** [comment]
@BWhitten thanks, updated the description

**Comment by htdvisser** [comment]
This is not going to get implemented in V2 anymore. It is implemented in The Things Stack (V3).
