### ISSUE TITLE
Label downlink MAC commands in data view

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/ttn#638]
This is a feature request for the console.

> What do you want to do?

Acknowledgements should be labelled in the data view on the console.

> What steps did you take?

Console -> application -> data. Get a device to send packets, requesting an ack.

> What went wrong or what is missing?

I see the acks as downlink messages on port 0. The payload and metadata is empty. On MQTT it looks liek this:
```
<appid>/devices/<devid>/events/down/sent {"payload":"YPAsASYgHQAdW4zy","message":{"app_id":"<appid>","dev_id":"<devid>","port":0},"gateway_id":"eui-7276fffffe010398","config":{"modulation":"LORA","data_rate":"SF7BW125","counter":29,"frequency":868300000,"power":14}}
```

> Do you have Screenshots?

![screenshot from 2017-06-23 13-57-10](https://user-images.githubusercontent.com/948278/27481410-bb624b0c-581c-11e7-922e-f29181e1ee63.png)

> What I expect to see

Looking at the port value, if it is port 0, we know it is LoRaWAN MAC commands. Label it as such.

We should be able to detect from the `payload` mqtt field what type of mac command it is. If we can do this, label is as such.

**Comment by htdvisser** [comment]
Requires #620
