### ISSUE TITLE
Rename —auth-server(s) to —account-server(s) (and alias)

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#643]
Everywhere in the docs the Account Server is denotes as such.
For the love of consistency let's also name out config options like that!

We can alias them to the old one for backwards compatibility.

**Comment by romeovs** [comment]
cc @htdvisser @dotpy3 @rvolosatovs @romeovs also in other repo's

**Comment by johanstokking** [comment]
cc @Sypheos also in other repos

**Comment by htdvisser** [comment]
To avoid confusion, we won't do this in v2 any more. In v3, the naming will be "identity server".
