### ISSUE TITLE
Test HTTP/MQTT handlers without starting server

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#65]
We don't have to start HTTP/MQTT servers to run their handler tests.

- `core/adapters/http/handlers/`
- `core/adapters/udp/handlers/`

See 

- [`core/adapters/http/handlers/statuspage_test.go`](https://github.com/TheThingsNetwork/ttn/blob/develop/core/adapters/http/handlers/statuspage_test.go) 

- [`core/adapters/mqtt/handlers/activation_test.go`](https://github.com/TheThingsNetwork/ttn/blob/develop/core/adapters/mqtt/handlers/activation_test.go) 

for some examples

*@KtorZ edit: changed `mqtt` to `udp` and added `mqtt` example*

**Comment by KtorZ** [comment]
Yep. 
Tests in `http` and `udp` have been re-used from before (before the distinction between adapters and handlers was made). Thus, at that moment, servers were required to enable testing. Not the case anymore, they should be rewritten.
