### ISSUE TITLE
HTTP + gRPC Component Debug Endpoints

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#653]
- [ ] Status
- [ ] PProf
- [ ] Health

**Comment by rvolosatovs** [comment]
there shouldn't be any need for https://github.com/TheThingsNetwork/ttn/blob/5ba1a1cb8961174568b612e067a73e7a8e41664a/cmd/pprof.go
https://golang.org/pkg/net/http/pprof/ is super easy to use and can be hidden behind a firewall. There should also be a way to bind it to a unix socket.
Btw, we could also use https://godoc.org/github.com/prometheus/client_golang/prometheus for metrics. @dotpy3 did you have a chance to look at Prometheus?

**Comment by htdvisser** [comment]
This was resolved by 873cf38bbe6e63b4dd6de1727439d731f12079b1
