### ISSUE TITLE
Add randomizers for all message types sent to NOC

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/ttn#658]
This is a **feature request** for **the backend**.
- [x] Gateway status
- [x] Router uplink
- [x] Router downlink
- [ ] Router status
- [x] Broker uplink
- [x] Broker downlink
- [ ] Broker status
- [ ] Handler status
- [ ] Network Server status

**Comment by htdvisser** [comment]
While at it, also move to a separate package to reduce the dependencies of (for example) clients.

**Comment by htdvisser** [comment]
Moved to https://github.com/TheThingsNetwork/api/issues/2
