### ISSUE TITLE
Add timestamps to all apex/log package log outputs

### ISSUE THREAD

**Issue by hoonppark** [TheThingsNetwork/ttn#660]
This is a feature request.

Currently all apex/log-package log outputs have no timestamps, making it difficult when debugging a problem.

I'd like to ask to add timestamps to all apex/log-package log outputs.

**Comment by htdvisser** [comment]
Although we usually use syslog, Docker logs or Elasticsearch, the timestamps are not displayed by default in the CLI. It might indeed be nice to add a CLI flag (`--log-timestamps`) that enables this. Could you submit a pull request for this?

**Comment by htdvisser** [comment]
There doesn't seem to be much interest for this feature. Archiving for now, but feel free to reopen if you want to work on this.
