### ISSUE TITLE
Migrate to github.com/TheThingsNetwork/api

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#662]
We currently use `github.com/TheThingsNetwork/ttn/api`, but this is being moved to `github.com/TheThingsNetwork/api`.

In the process we are making some changes to the generated Go code in the new `api` package:

- `Id` is renamed to `ID`
- `Eui` is renamed to `EUI`
- Some fields are now marked as non-nullable

Please report any other improvements in https://github.com/TheThingsNetwork/api/issues

**Comment by rvolosatovs** [comment]
As far as I understand, packages like `api/stats` and `api/ratelimit` are not moved, or are they? Please specify concrete packages being moved

**Comment by htdvisser** [comment]
The packages that contain `.proto` files

```
.
├── broker
├── discovery
├── gateway
├── handler
├── logfields
├── monitor
├── networkserver
├── protocol
│   └── lorawan
├── router
└── trace
```

**Comment by rvolosatovs** [comment]
what should happen with the Clients, i.e. `monitor.Client` ?

**Comment by htdvisser** [comment]
There are a number of things that will have to be moved to the new API package:

- Convenience functions (for example `*DeduplicatedUplinkMessage.InitResponseTemplate()`)
- Some implementations (for example in `trace`)

There are a number of things that will need a new place somewhere else:

- `Message`/`Payload` (un)marshaling
- Reference Servers
- Stream clients
- Stream servers
- gRPC Client Pool
- Ratelimiting
- `stats`

Or have to be removed completely:

- Discovery client "overlay"
- Handler Manager client "overlay"

**Comment by rvolosatovs** [comment]
I will take care of that also then

**Comment by htdvisser** [comment]
Great! Nice to finally clean this mess up 😄
