### ISSUE TITLE
Add more info to announced components in Discovery Server

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/ttn#664]
This is a **feature request** for **the Discovery Server**.

See https://github.com/TheThingsIndustries/console/issues/381

It would be nice if we can add extra information to an announcement. We should add:
- an `Emoji` or `IconURL` field
- an `Operator` field, with information about the operator (name, homepage, ...)

**Comment by johanstokking** [comment]
Also contact uri (maybe link-like, so `mailto:` or `https://`)

**Comment by htdvisser** [comment]
Moving this to v3. We'll have to come up with a different mechanism, considering that there likely won't be a discovery server in v3...
