### ISSUE TITLE
I.P address refused to connect

### ISSUE THREAD

**Issue by monkmahadeva** [TheThingsNetwork/ttn#675]
Hi,
I have confiured the loraserver in my own linux server using https://www.loraserver.io/, all the components necessary have been installed in the same server on the localhost. Although when i try to run the Gui of the server in my windows using the I.P address of the server. It somehow refuses to connect. Can anybody tell me why this is happening??

**Comment by johanstokking** [comment]
@monkmahadeva please file the issue here: https://github.com/brocaar/loraserver
