### ISSUE TITLE
[lmic-c1.51] How can get a confimation when my node joined a gateway or not

### ISSUE THREAD

**Issue by pierrot10** [TheThingsNetwork/ttn#676]
Good day.

I am new and I confured a gateway.
I also have anode with IC880a.
I am using that library with my node
https://github.com/things4u/LoRa-LMIC-1.51/tree/master/libraries/lmic-v1.51

When I am at home, my data are sent to TTN.
Actually I left my place and I am about 8km from my flat.
There is another gateway but I am in a building.

I am sure I can not reach a gateway, but my terminal print me this

> Opmode check: EV_TXCOMPLETE, time: 1101
> Sent: 1

Someone know that library and some know if there is solution to confirm that my node can reach a gateway?

If my node is out of a gateway range or can not send data throug a gate, I want it to print me a message and desactivate some fonction, as sending data..., and periodicaly chec if a gateway is available.

Thank a lot for any information, you could provide me

**Comment by htdvisser** [comment]
See https://github.com/things4u/LoRa-LMIC-1.51/issues/13
