### ISSUE TITLE
Add airtime to message metadata

### ISSUE THREAD

**Issue by gonzalocasas** [TheThingsNetwork/ttn#682]
This is a **feature request** for **the backend**.

> What do you want to do?

I would like to be able to analyze and understand the air time used by each device over time.

> What is missing?

The airtime is currently available in the TTN console but only as an *on-the-fly* calculation ([airtime calculator](https://docs.google.com/spreadsheets/d/1voGAtQAjC1qBmaVuP1ApNKs1ekgUjavHuVQIXyYSvNc/edit?usp=sharing)). However, this value is not accessible via any API. It would be very useful to have this value (even if it is an estimate), integrated into the payload of the messages, as part of the metadata.

**Comment by gonzalocasas** [comment]
Implementation might be linked to #646.

**Comment by htdvisser** [comment]
I like the idea. Then at least we don't have to worry about inconsistent implementations anymore.
