### ISSUE TITLE
Downlink to LoRa devices

### ISSUE THREAD

**Issue by mazareth** [TheThingsNetwork/ttn#686]
Hi everybody.
This is a question for an integration.

> What do you want to do?
use a watteco temp/hum sensor

> What steps did you take?
Add the device on thethingnetwork, thats work

> What went wrong or what is missing?
1 - I don't understand why thethingnetwork send a message with empty payload after the temp or hum frame. Where this message come from?
2 - I want to send configuration message to my device but i don't understand how to do.
I try in the dowlink tab... that appear in application data but nothing more...
Do you have explanation?

> Do you have Screenshots?
![image](https://user-images.githubusercontent.com/19725586/33473274-05362e10-d676-11e7-8b3d-835e7e7c239c.png)

![image](https://user-images.githubusercontent.com/19725586/33473520-092c7262-d677-11e7-919f-01fa2d215832.png)

![image](https://user-images.githubusercontent.com/19725586/33473543-23a6f7f2-d677-11e7-98c4-024fd600b263.png)

> What kind of OS/Browser/Gateway are you using? Which version?
packet_forwarder on pi with picoGW
drive thethingnetwork by chrome on windows 7

> What are the IDs and EUIs of your Device/Gateway? (if applicable)
gateway : eui-414456414e54454e

**Comment by johanstokking** [comment]
@mazareth thanks for reporting.

1. Payload on FPort 0 are MAC commands, these are sent by the network server as per LoRaWAN specification;
2. Seems like you do the configuration right. You can send the downlink by pressing the button. You will see it appear scheduled in the Application Data, and then sent off the next time there's an opportunity to send

**Comment by mazareth** [comment]
Hi Johan,
Thanks for 1.

For 2 - Do you know where the opportunity to send is calculated?
What's the Fport change?
What's the confirmed checkbox change?

**Comment by johanstokking** [comment]
@mazareth yes, on class A the network has an opportunity to send only directly after an end device's uplink transmission.

I'm closing this issue as I think it is resolved.

Did you know that there's a #support channel on our Slack? Also, there's the public forum.

**Comment by mazareth** [comment]
@johanstokking  no i don't know where i can't ask question.
Could you give me a link?

And how can i change the class of the network?

**Comment by johanstokking** [comment]
Class C is experimental in TTN Stack V2 (this version), but class B and C will be generally available in TTN Stack V3, launched 2018 Q1.

**Comment by htdvisser** [comment]
See [this post on the forum](https://www.thethingsnetwork.org/forum/t/ttn-network-stack-v3-central-1/14991/6?u=htdvisser)
