### ISSUE TITLE
No ADR LinkADRReq in downlinks other than ACK

### ISSUE THREAD

**Issue by atoy40** [TheThingsNetwork/ttn#688]
LinkADRReq are never included into downlink :

- If confirmed uplink are sent : no problem, a LinkADRReq is included in the first ACK, and my device update his rate.
- If unconfirmed uplink are sent, and then some downlink are generated and sent to the node : downlinks never include LinkADRReq (I've check it on the online lora packet decoder using packet going through my gateway), even after more than 20 frames sent (so the history queue on the server is full). I'm absolutely sure the downlink come to the end-device because it's log by my gateway and the payload is displayed by the device through his serial port.

Thanks. Anthony.

**Comment by htdvisser** [comment]
This is not going to get fixed in V2. 

The Things Stack (V3) does not have this issue.
