### ISSUE TITLE
TTN Console might need different default for Router when selecting Australia frequency plan?

### ISSUE THREAD

**Issue by avbentem** [TheThingsNetwork/ttn#689]
This is a **bug report** for **the console**.

> What do you want to do?

Add a new gateway in Australia.

> What steps did you take?

Select frequency plan "Australia 915MHz". According to [the Server Addresses page](https://www.thethingsnetwork.org/wiki/Backend/Connect/Gateway) on the Wiki, this apparently needs `router.au.thethings.network` in the gateway configuration, which (today) is an alias for `thethings.meshed.com.au`. 

> What went wrong or what is missing?

The Router dropdown defaults to `ttn-router-asia-se (asia-se.thethings.network:1901)`. However, it seems `meshed-router (thethings.meshed.com.au:1901)` is a better choice?

(Also, _"pick a router that is in a region which is close to the location of the router itself"_ could use some different wording, as "router" seems to be used for two different things here?)

> Do you have Screenshots?

![image](https://user-images.githubusercontent.com/1497002/34079723-6e752e70-e333-11e7-9fbe-44403a6e2a8c.png)

**Comment by htdvisser** [comment]
Done.
