### ISSUE TITLE
ADR support in AS923

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#696]

**Comment by toruuetani** [comment]
I think this title may be not appropriate.
If you use frequency plans, please separate Japanese plan from AS923.
In Japan, frequency plans are 920.6MHz(CH24) - 928.0MHz(CH61), even if we usually use below 923.4MHz.
- below 250mW: 920.6MHz - 923.4MHz
- below 20mW: 920.6MHz - 928.0MHz

**Comment by htdvisser** [comment]
We follow the naming of the LoRaWAN Regional Parameters specification document and the Japanese configuration is based on the AS923 band.

**Comment by toruuetani** [comment]
Thank you for change.
Your code has no problem. 
Because frequency plans are not used.
