### ISSUE TITLE
Review and add logs 

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#7]
We have to agree on the log format: 

- Which pieces of information are important to know ? 
- How can we format the output such that it is easy to parse ?
- How many different levels do we need ?

etc..

**Comment by johanstokking** [comment]
Reopening this issue because we need an additional round of review here.

See for example "unexpected error" when there's no broker found (this is expected behavior and not an error) and "uplink device not found" is too vague. Please check runtime logs and adjust where necessary

**Comment by htdvisser** [comment]
It should be more clear what log messages mean now.
