### ISSUE TITLE
DevEUI not valid by device registration on-join

### ISSUE THREAD

**Issue by neolinux** [TheThingsNetwork/ttn#702]
This is a **bug report/feature request/question/...** for **the website/the backend/ttnctl/the console/the NOC/an integration/...**.

> What do you want to do?
Activate device registration on-join on one Application

> What steps did you take?
Downloaded the ttn-cli x64 for Windows
Launched this command:
./ttnctl-windows-amd64.exe device register on-join demo C7E94AC4B4AED1E8D6F78E**********

> What went wrong or what is missing?
After that Command i became this error back:

  INFO Using Application                        AppEUI=70B3D57ED000B101 AppID=pm-auto
  WARN On-join registration does not follow LoRaWAN best practices. Unless you implement additional security
  WARN measures, it may corrupt your entire application if even one of your devices gets compromised.
  INFO Discovering Handler...                   Handler=ttn-handler-us-west
  INFO Connecting with Handler...               Handler=us-west.thethings.network:1904
  INFO Application does not have a RegisterOnJoinAccessKey
  INFO Looking for existing key...
  INFO Using existing key...
 FATAL Could not register Device                error=Could not set device on Handler: Invalid Device: Invalid Device: Invalid LoRaWANDevice: DevEUI not valid: can not be empty source=Wrap: /go/src/github.com/TheThingsNetwork/ttn/utils/errors/errors.go:222

**Comment by johanstokking** [comment]
Thanks! We'll have a look at this. This could be regression when validating values.

**Comment by neolinux** [comment]
Thank You,

i will wait for a Solution.

**Comment by johanstokking** [comment]
@dotpy3 will look into it, thanks.

**Comment by jpmeijers** [comment]
I am also affected by this bug.

**Comment by neolinux** [comment]
Any news?

**Comment by htdvisser** [comment]
This will be resolved in the next release. We were a bit too strict with our validations. Please do note that on-join registration is typically not a great idea, and we may stop supporting it in v3.
