### ISSUE TITLE
Show warning in device application data for too much airtime

### ISSUE THREAD

**Issue by amkuipers** [TheThingsNetwork/ttn#706]
This is a **feature request.** for **the console**.

> What do you want to do?

As developer of software for a device, I would like to see a warning when my device sends too fast and/or too much data within a period. This feature might be based on the the last N messages (for example 5 or 10), or M minutes in the web page with application data for a device. 

This might just be a browser javascript calculation, parsing the messages displayed in the 'data' page.

> What steps did you take?

For a device, go to application data, next to pause and clear, this new feature can be added as a button (the user selects to analyse the sending pattern). Or, the warning can be 'automatic', for example when the frame-counter-checks is off; message counter is reset and less than 100.

> What went wrong or what is missing?

As a developer I could make airtime calculations. Often this is not done. A message is then sent every minute. By having a feature to show the warning that the airtime should be lowered, it might help. Developers can then tune their software before the device is deployed, or the software is deployed on many devices.

> Do you have Screenshots?

No.

> What kind of OS/Browser/Gateway are you using? Which version?

Not relevant.

> What are the IDs and EUIs of your Device/Gateway? (if applicable)

Not relevant.

> What do your configuration files look like?

Not relevant.

> What do your log files look like?

Not relevant.

> Can you fix this yourself and submit a pull request?

No, this is not a fix. Also airtime calculation is not my expertise, that is also why I propose this feature.

**Comment by htdvisser** [comment]
This is not going to get fixed in V2. 

For v3 we're tracking this feature in https://github.com/TheThingsNetwork/lorawan-stack/issues/3864
