### ISSUE TITLE
Add at least location as part of device events

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/ttn#713]
This is a **feature request** for **the backend**.

> What do you want to do?

Publish (at least) location as part of the device events.

This is especially relevant for the Collos integration, which updates the device registry and triggers a device update event. If we add the device's location as part of the payload, applications can subscribe to location updates through MQTT.

> What went wrong or what is missing?

Data is `nil`, see https://github.com/TheThingsNetwork/ttn/blob/develop/core/handler/manager_server.go#L228

**Comment by toruuetani** [comment]
I think that Collos has three algorithm for resolving location.
So I think that update events need not only location but also algorithm.

**Comment by johanstokking** [comment]
In V2 we have only one location per device in the registry.

Do note that the idea of Collos is that it resolves the best possible; in the order of WiFi, LoRa TDOA to LoRa RSSI. It is only for debugging purposes to have multiple endpoints enabled, but this is not supported in our device registry.

**Comment by htdvisser** [comment]
Some notes for @Sypheos:
- There is no need to send the entire Device on every update. We can quite easily filter only the changed fields with `dev.ChangedFields()`
- We should **not** send sensitive fields such as keys, nonces, ...  
- We should probably send the jsonpb-marshaled (not std lib `encoding/json`!) for consistency with what grpc-gateway returns.

**Comment by toruuetani** [comment]
OK, I understand.
We are interested only in TDOA.
I think that RSSI is TDOA's preliminary exercise.

**Comment by johanstokking** [comment]
If you use the `Lora Wifi` recipe, you'll get the fallback automatically. Just don't pass WiFi; https://apiportal.preview.collos.org/docs/services/localization-lora-recipes/operations/59e9b2a367ba551b780cd259?

**Comment by toruuetani** [comment]
OK, I understand.

**Comment by toruuetani** [comment]
What topic does this event send to ?

**Comment by johanstokking** [comment]
@toruuetani It will be part of the updated management event, see https://github.com/TheThingsNetwork/ttn/tree/develop/mqtt#management-events

**Comment by toruuetani** [comment]
OK, thanks.

**Comment by Sypheos** [comment]
@toruuetani Device data event now contain location PR #715 is merged

**Comment by toruuetani** [comment]
@Sypheos Great !
I'm looking forward to evaluate this feature.

**Comment by htdvisser** [comment]
I expect this to be deployed to production early next week 👍

**Comment by toruuetani** [comment]
OK,  I will wait for update.
Thank you !

**Comment by toruuetani** [comment]
How is progress?

**Comment by htdvisser** [comment]
The updates are currently being rolled out. All regions with `ttn-` prefix are already updated.
