### ISSUE TITLE
MQTT IP Adress from TTN

### ISSUE THREAD

**Issue by MiguelESP89** [TheThingsNetwork/ttn#720]
This is a **bug report/feature request/question/...** for **the website/the backend/ttnctl/the console/the NOC/an integration/...**.

> What do you want to do?
Hey we want to add a MQTT Broker to FHEM. Our Networksecurity needs a IP Adress from the MQTT Server from TTN to get Data from our Sensors over the 1883 Port.

Thank you very much

**Comment by johanstokking** [comment]
You can do a DNS lookup of the concerning region's MQTT server for application data. We do not guarantee IP addresses to be static.
