### ISSUE TITLE
Establish bridge connection to my own mosquitto broker

### ISSUE THREAD

**Issue by FranciscoGJ** [TheThingsNetwork/ttn#721]
How can I establish a bridge connection between my mosquitto broker and ttn broker mqtt??

**Comment by johanstokking** [comment]
There's some good documentation about this; http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

It comes down to a client that subscribes to a TTN MQTT server and publishes to yours, and back. That may be an intermediate client, or builtin bridging functionality of Mosquitto.

**Comment by FranciscoGJ** [comment]
I tried to implement this functionality but I did not succeed. This is my config file in my mosquitto broker.
`# Bridge to ttn

connection br-ms-to-ttn
address us-west.thethings.network:1883
cleansession false
clientid br-ms-ttn
bridge_protocol_version mqttv311
bridge_insecure false
start_type automatic
remote_username ******
remote_password ******
notifications true
try_private true
topic ttn in 0`
But I could not establish the connection.

**Comment by johanstokking** [comment]
Without any context (i.e. error messages) there's no way to debug this. Also, I don't think this is specific to the TTN MQTT server.

**Comment by FranciscoGJ** [comment]
I feel them, this is the error

1529471394: Config loaded from /etc/mosquitto/conf.d/bridge.conf.
1529471394: Opening ipv4 listen socket on port 1883.
1529471394: Opening ipv6 listen socket on port 1883.
1529471394: Connecting bridge br-ms-to-ttn (us-west.thethings.network:1883)
1529471425: Connecting bridge br-ms-to-ttn (us-west.thethings.network:1883)
1529471425: Connection Refused: unacceptable protocol version
1529471425: Socket error on client local.br-ms-ttn, disconnecting.

I think the error is in the mosquitto configuration but I do not understand what it can be.

**Comment by FranciscoGJ** [comment]
I think I will implement that solution. Thanks for the support
