### ISSUE TITLE
How to identify when a device or gateway is down?

### ISSUE THREAD

**Issue by FranciscoGJ** [TheThingsNetwork/ttn#723]
Hi! I am using Data API MQTT and I would like to know how I can identify if a device or gateway is down.

Any suggestions?

**Comment by KrishnaIyer** [comment]
HI @FranciscoGJ 
You can use the `cli` to check the status of the gateway/device:
https://www.thethingsnetwork.org/docs/network/cli/quick-start.html

If you are using your own private instance of the TTN Network, make sure to set the `mqtt address` and `router-id` to the ones of your network in the cli using the `--mqtt-address` and `--router-id` options.
