### ISSUE TITLE
End device(endnode) not receiving downlink data from server

### ISSUE THREAD

**Issue by ashok410** [TheThingsNetwork/ttn#725]
Hi ,
I am getting issue to receive downlink packet to the end device from the server.
I am receiving uplink acknowledgement from the server(automatically sending ACK from server to the endnode) but i am not able to receive downlink messages which are scheduled by me (using mqtt + nodered application.)

please help me to solve this problem
Thanks in Advance.
Regards,
Ashok.

**Comment by KrishnaIyer** [comment]
hey @ashok410. There isn't enough information in your description. Please use the provided issue template while reporting issues.

**Comment by ashok410** [comment]
Hi Krishna Iyer Easwarn,
 Thanks for your reply, The problem is solved.
Regards,
Ashok
