### ISSUE TITLE
Support for custom frequency plan

### ISSUE THREAD

**Issue by j4zzcat** [TheThingsNetwork/ttn#726]
This is a feature request for the backend and the console.
There are situations when a custom frequency plan is desirable. In this context, 'custom' means:
- the ability to enable and disable and otherwise change the configuration (BW, SF and CR) of certain channels within a standard plan (i.e., one that is defined in the LoRaWAN specification). For example, within the US plan, allow the user to disable channels 8-24, change the SF supported by channel 11 etc. And; 
- create a completely new plan that defines its own frequency range, join channels, duty cycle etc. For example, (1) add channel 867.551100MHz as a join channel to the EU plan; (2) create a new plan for the 915-917MHz range etc.

Such capability is useful in the following situations:

- Testing and benchmarking gateways and nodes in different settings
- Debugging noisy channels and channel settings
- Overcoming interference that is specific to a certain area
- Trying out new ideas

**Comment by KrishnaIyer** [comment]
Oops. 

@j4zzcat: Can you please use our template while creating issues?

What exactly do you mean by `custom frequency plan`? can you provide some examples?

**Comment by htdvisser** [comment]
This will likely not be possible on the public community network, but with our v3 stack, some of this should be possible in a private network.

Things that we will most probably **never support**:

- Change the supported SFs of US915/AU915/CN470 channels - This would make the network non-compliant with LoRaWAN
- Change the fixed join channels of EU868/CN779/AS923/... - This would make the network non-compliant with LoRaWAN

**Comment by j4zzcat** [comment]
Indeed, my intention was that this feature be used in private networks.

**Comment by htdvisser** [comment]
In v3 it is now possible to configure a network server with a custom frequency plan repository (typically a fork of https://github.com/TheThingsNetwork/lorawan-frequency-plans).
