### ISSUE TITLE
Does Python-App SDK for TTN module support HTTP Protocol

### ISSUE THREAD

**Issue by AnilkumarKomanduru** [TheThingsNetwork/ttn#727]
Does Python-App SDK for TTN module support HTTP Protocol ?

Currently we are facing issues with MQTT Protocol while accessing TTN servers using TTN python Library

In corporate world due to the security issues they have given us the provision only for HTTP.

Now I would like to know, Does the Python-App SDK support for HTTP protocol also ?

**Comment by htdvisser** [comment]
No. The only way to get your data from TTN is to use the MQTT protocol or to use one or more of the available integrations.

Also note that the SDKs are supposed to run on servers (which should have unrestricted access to the internet). Those servers then expose the data to end users (which may be behind a corporate firewall).
