### ISSUE TITLE
Change CLI help message for adding gateway collaborators

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/ttn#730]
This is a cosmetic **bug report.** for **ttnctl**.

> What do you want to do?

Add a collaborator to a gateway using the CLI.

> What steps did you take?

` $ ttnctl gateways collaborators add --help` 
(Not the best methods to get help i agree)

> What went wrong or what is missing?

```
Usage:
  ttnctl gateways collaborators add [AppID] [Username] [Rights...] [flags]
```
The description must say `[GatewayID]` instead of `[AppID]`.
Though this is sort of obvious, it might confuse new users.

> Do you have Screenshots?

<img width="1355" alt="screen shot 2018-07-18 at 11 54 30 am" src="https://user-images.githubusercontent.com/13186113/42874407-5e19117c-8a81-11e8-9842-604d734e8615.png">

> What kind of OS/Browser/Gateway are you using? Which version?
 
This is applicable to all.

> What are the IDs and EUIs of your Device/Gateway? (if applicable)

NA

> What do your configuration files look like?

NA

> What do your log files look like?

NA

> Can you fix this yourself and submit a pull request?

Yes.

**Comment by htdvisser** [comment]
This is not going to get implemented in V2 anymore.
