### ISSUE TITLE
Make connection errors between services more verbose

### ISSUE THREAD

**Issue by Niondir** [TheThingsNetwork/ttn#731]
This is a **feature request** for **the backend**.

> What do you want to do?

Setup a private TTN

> What steps did you take?

Basically this: https://github.com/lobaro/ttn-private-network/issues/1

> What went wrong or what is missing?

I missed a port in the `ttn.yml` configuration of the broker

I got the following error when turning on "debug logs" for the broker.

```
DEBUG grpc: addrConn.createTransport failed to connect to {networkserver.local.thethings.network 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: address networkserver.local.thethings.network: missing port in address". Reconnecting...
```

Even worse, the handler did not started because the broker did not and subsequent errors were leading to the handler, but the miss configuration was inside the handler.

I would love to see any kind of connection errors / retries inside the INFO or ERROR level logs.

**Comment by htdvisser** [comment]
This is not going to get fixed in V2 anymore.
