### ISSUE TITLE
Custom Frequency compliance, raw Lora 

### ISSUE THREAD

**Issue by GitTibbe** [TheThingsNetwork/ttn#734]
This is a **question.** for **an integration**.

I am setting up a private lora network (not LoraWAN) in the 868MHz range, and I am wondering if it is possible to set 3 Gateway channels in the g3 (869.4 – 869.65 MHz): 10% band with 125KHz Bandwidth?

For example:
1: 869.4
2: 869.525
3: 869.65

What is the minimum margin possible between frequencies?
How does the bandwidth affect the legal limitations?

Thanks in advance!

**Comment by htdvisser** [comment]
This repository is for the backend systems of The Things Network's LoRaWAN network server, so we can't really help you with this particular question. You may have more luck on our [forums](https://www.thethingsnetwork.org/forum/) or by contacting your local regulator.
