### ISSUE TITLE
MQTT documentation

### ISSUE THREAD

**Issue by grahamehorner** [TheThingsNetwork/ttn#743]
This is a question for the backend and integration with the MQTT service.

What do you want to do?
I'm looking to develop a AzureFunctions Trigger that listens to messages/topics on the MQTT/AMQP service for a given application; and allows the developer to capture the message(s) received routing/processing message in the cloud

What steps did you take?
I'm able to successfully connect to the MQTT service

What went wrong or what is missing?
However when subscribing to events/devices I don't receive messages?

Please can you assist with the MQTT topic naming convention and/or where I may find documentation with regard how MQTT is used for application/device events

**Comment by htdvisser** [comment]
You can find the MQTT documentation [on our Docs site](https://www.thethingsnetwork.org/docs/applications/mqtt/api.html) which pulls it from [this repository](https://github.com/TheThingsNetwork/ttn/tree/develop/mqtt).

If you want to see all events (for debugging purposes), you can use `mosquitto_sub` to subscribe to the wildcard topic: `mosquitto_sub -u "your-app-id" -P "ttn-account-v2.xxx..key..xxx" -d -t "#"`. This should print out everything that is published to your application, including the topics where the messages are published.
