### ISSUE TITLE
In TTN Console, changing ABP device settings (even just its description) resets the frame counters

### ISSUE THREAD

**Issue by avbentem** [TheThingsNetwork/ttn#746]
This is a **bug report** for **the console**.

> What do you want to do?

Change some settings of a device in TTN Console.

> What steps did you take?

Changed the human-readable device's description. (Same goes for any other setting, including changing "Frame Counter Checks".)

> What went wrong or what is missing?

Both the uplink and downlink frame counters were reset to zero, basically requiring the device to be reset.

If this is by design, then a warning should be shown.

The counters are not reset when using `ttnctl` rather than TTN Console.

> Do you have Screenshots?

N/A.

> What kind of OS/Browser/Gateway are you using? Which version?

N/A.

> What are the IDs and EUIs of your Device/Gateway? (if applicable)

N/A.

> What do your configuration files look like?

N/A.

> What do your log files look like?

N/A.

> Can you fix this yourself and submit a pull request?

No.

**Comment by johanstokking** [comment]
Thanks, we're adding some explanation in the V3 Console for this.

**Comment by avbentem** [comment]
Hmmm, that's weird, I can really reproduce this every time:

![github-ttn-746](https://user-images.githubusercontent.com/1497002/48054114-c4f7d180-e1ac-11e8-8b9d-9dcb97381e41.gif)

(Sorry for the slow GIF...)

**Comment by avbentem** [comment]
@htdvisser Indeed, for me it's only happening with an ABP device. Not such a common problem after all then, though a warning might be nice...

(Using `ttnctl` for the very same ABP device does not reset the counters.)

**Comment by htdvisser** [comment]
This is not going to get fixed in V2 anymore.
