### ISSUE TITLE
Addition of Python Brackets instead of Braces on Console

### ISSUE THREAD

**Issue by brentru** [TheThingsNetwork/ttn#749]
Hi TTN Team,

I'd like to request a feature on the web console for applications which would allow for easy inclusion of Python-nodes, in addition to C/C++ based nodes.

In Python, `{ }` creates a dict, and `[ ]` creates a list: they're both collections of objects, but they aren't the same. 

Currently the TTN Console only prints keys formatted with braces `{ }`. Would it be possible to add a button or switch switch to assign brackets `[ ]` around the keys?

**Comment by brentru** [comment]
Great, thanks!

**Comment by htdvisser** [comment]
I submitted https://github.com/TheThingsNetwork/lorawan-stack/pull/155 for v3 to only render the contents, and leave the braces/brackets out. Toggling through different array/list styles for different languages wouldn't improve the user experience.
