### ISSUE TITLE
ADR request is not sent 

### ISSUE THREAD

**Issue by davidonet** [TheThingsNetwork/ttn#757]
I have a gateway connected to ttn in my office.
I registered a device, sending an uplink every 3 minutes, wait at least 24 hours placed 5 meters from the gateway. When I checked on console, the uplinks are still in SF12.
I checked the downlink : it works.

I was expected in https://www.thethingsnetwork.org/docs/lorawan/adr.html an ADR :
Point 3 : 

> An ADR request is sent when we have enough measurements and the device is using DR0 (SF12BW125 in most regions).

I've never seen this downlink, my device have ADR bit setted.

So I manage to modify the device to make it set the ADRACKReq even in SF12 and then we receive LinkADRReq and the device switch to sf7. 

This is not compliant with LORAWAN : LinkADRReq should be set after 64 uplinks **only if not sending in SF12**.

**Comment by htdvisser** [comment]
This should be better with #758 merged. This isn't deployed yet to the public community network. Assigning @Sypheos to test this. If everything is ok, we can create a PR to master and release+deploy a new version. cc: @johanstokking
