### ISSUE TITLE
Auto-updating Backend

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#76]
We should investigate the possibilities of automatically updating backend components. 

Things to keep in mind:
- Security (Sign code/binary with GPG key)
- ...

**Comment by KtorZ** [comment]
What do you mean by automatic update ?

**Comment by htdvisser** [comment]
Something like this: https://github.com/sanbornm/go-selfupdate

**Comment by KtorZ** [comment]
:o ... Did you heard about Skynet already ?
Could be a nice feature indeed, thanks for the clarification.

**Comment by htdvisser** [comment]
b938766fff51c37c295c55167224e499a40bffcf adds the `selfupdate` command to `ttn` and `ttnctl`. Periodically updating servers should be explained in the docs.
