### ISSUE TITLE
Can't copy data

### ISSUE THREAD

**Issue by edgale** [TheThingsNetwork/ttn#763]
This is a **bug report/question** for **the website/the console**.

> What do you want to do?
I got a application set up and in there a view sensors. I want to copy the data from a message of a sensor, but can't because the message is to long. I can't mark the data and copy and can't reach the copy button.
> Do you have Screenshots?
![image](https://user-images.githubusercontent.com/4374065/59739164-0cc2f900-9264-11e9-8e7f-626a1adb5112.png)
> What kind of OS/Browser/Gateway are you using? Which version?
Google Chrome Version 75.0.3770.90 (64-Bit)

**Comment by htdvisser** [comment]
When I single-click on any character in the payload field, the entire field is selected. Have you tried that?

@kschiffer @bafonins I don't think we'll fix this for v2 anymore, but please confirm that in v3 large payloads also render properly.

**Comment by edgale** [comment]
Hi @htdvisser , thanks for your reply. I tired clicking on any character but nothing happens. I can't select the data.

**Comment by htdvisser** [comment]
Ah sorry, I overlooked that you're using Chrome. It works in my Firefox, but when I try to copy the contents of the bytes field in Chrome, I can only do that with the copy button. There seems to be a `user-select: none` in there somewhere that prevents selection.

**Comment by htdvisser** [comment]
This isn't going to get fixed in V2 anymore, and it should work okay in The Things Stack (V3).
