### ISSUE TITLE
Export devices as V3 JSON

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#764]
This is a **feature request** for **ttnctl**.

> What do you want to do?

I want to migrate devices from v2 to v3.

> What steps did you take?

- In v2: `ttnctl devices list`, `ttnctl devices info [id]`
- In v3: `ttn-lw-cli end-devices create ...`

> What went wrong or what is missing?

It's too much work. It would be a lot easier if there was a `ttnctl devices export [id]` that would print V3 JSON so that I can pipe it directly into `ttn-lw-cli end-devices create`.

> Can you fix this yourself and submit a pull request?

Yes

**Comment by htdvisser** [comment]
When this is done and working, we may want to add the same to the console.

**Comment by htdvisser** [comment]
Work started in https://github.com/TheThingsNetwork/ttn/compare/feature/v3-export

@rvolosatovs please see what other fields we may need to transfer when migrating existing devices from v2 to v3.

**Comment by johanstokking** [comment]
@neoaggelos is taking this over

@htdvisser can you let @neoaggelos know if the branch that you mentioned is still relevant and like we want this to be?

**Comment by htdvisser** [comment]
This was practically done. Only thing left was for @rvolosatovs to confirm what MAC settings need to be set in the network server.

**Comment by johanstokking** [comment]
OK. @neoaggelos please coordinate with @rvolosatovs and file an issue in `lorawan-stack` for documenting migrating devices from V2 to V3 via CLI.

**Comment by neoaggelos** [comment]
> OK. @neoaggelos please coordinate with @rvolosatovs and file an issue in `lorawan-stack` for documenting migrating devices from V2 to V3 via CLI.

There is https://github.com/TheThingsNetwork/lorawan-stack/issues/1685

**Comment by neoaggelos** [comment]
I'm having trouble telling apart OTAA from ABP devices from v2 with ttnctl. What I've seen is that all devices (both OTAA and ABP) have `ActivationConstraints` equal to `Local`. The console seems to be  telling them apart by looking up the usages for devaddr prefixes in https://console.thethingsnetwork.org/api/handlers.

`ttnctl discover broker --metadata` is the closest I can get, but it does not include the usages of the prefixes.

Can we retrieve this info from the handler itself?

**Comment by johanstokking** [comment]
I don't think you can get this from the Handler, but you should be able to get this from the V2 NS.

**Comment by htdvisser** [comment]
The v2 API only allows talking to the Handler, so you can't talk to the NetworkServer.

The difference between OTAA and ABP devices in v2 is that OTAA devices have an AppKey and ABP devices don't.
