### ISSUE TITLE
Device Description is being lost

### ISSUE THREAD

**Issue by Recodify** [TheThingsNetwork/ttn#775]
This is a bug report for the console

> What do you want to do?

Update a device description

> What steps did you take?

1. Edit the device description using the console. (Device settings tab)

> What went wrong or what is missing?

Description shows against the device briefly but then is lost. The same behavior has been noted using the application manage http api.

This only seems to affect this single application, not seen the issue with others but this application has been reflecting this issue for some weeks now.

> Do you have Screenshots?

https://www.youtube.com/watch?v=q1ZgXlx8ge4&list=PLBED30EB02A63E1FB&index=11&t=0=#'

> What kind of OS/Browser/Gateway are you using? Which version?

Ubuntu 18.04. Tested with Chrome and Firefox (latest versions)

> What are the IDs and EUIs of your Device/Gateway? (if applicable)

ApplicationId: elsys-ersco2-live
DevicesIds: [a81758fffe04ab69, a81758fffe04ab6a, a81758fffe04b48b, a81758fffe04b490]

**Comment by htdvisser** [comment]
This isn't going to get fixed in V2 anymore. V3 should not have this problem.
