### ISSUE TITLE
Improve downlink rate limit of handler

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/ttn#786]
> What do you want to do?

Improve the downlink rate limit of the handler

> What steps did you take?

Recreated routing services as per the procedure, after that for a brief period downlinks were not routed back to devices with warnings in broker container.
> What went wrong or what is missing?

There is a hard limit of 125 downlinks per second (https://github.com/TheThingsNetwork/ttn/blob/master/core/broker/server.go#L135)
Due to which the following error is seen in the broker
2020-07-15T15:46:05.336154398Z WARN Handler reached downlink rate limit HandlerID= handler Wait=1m0.104852599s
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/76
> Do you have Screenshots?

...
> What kind of OS/Browser/Gateway are you using? Which version?

...
> What are the IDs and EUIs of your Device/Gateway? (if applicable)

...
> What do your configuration files look like?

...
> What do your log files look like?

...
> Can you fix this yourself and submit a pull request?

Not sure. Testing would require a high traffic instance.

**Comment by htdvisser** [comment]
This isn't going to get fixed, but the migration tool now respects the V2 rate limits.
