### ISSUE TITLE
Resources Management

### ISSUE THREAD

**Issue by KtorZ** [TheThingsNetwork/ttn#79]
Currently, the network only allows the creation of resources (activations). There's no way to retrieve, update or delete any of these resources. Plus, the initial creation is triggered by an MQTT message, which isn't convenient (no response / confirmation). 

Thus, we need to provide at least CRUD operations for those resources. Here's my proposal:

@johanstokking @htdvisser 

## Handler Http Adapter
We need to create a basic http handler that can be plugged into the current http handler of the Handler. 
Using a reference to the HandlerServer, it can forward http request to the Handler and reply accordingly to applications. 
That http-handler listens for requests of the following form:

All request are expected to accept the following `Content-Types`:

- `application/json`
- `application/msgpack` 

Each request described but the two first ones needs to provide a header `Authorization` with a token provided by the network during the first or the second request (which are merely registration and authentication). That token is the result of a ciphered combination of a salt + app_eui, using a 256-bytes secret key.

**`[PUT] /applications/:app_eui`**
result: 201 Created + (string) A valid authentication token

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
password | string | A secret password used by the application to register itself 

error | source
---|---
400 Bad Request | The password is too short / too long or the app_eui is invalid
409 Conflict |  An application is already registered with that app_eui
500 Internal Server Error | Unable to communicate internally for an unknown reason

**`[GET] /applications/:app_eui`**
result: 200 OK + (string) A valid authentication token

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
password | string | A secret password used by the application to register itself 

error | source
---|---
400 Bad Request | The password is missing or the app_eui is invalid
403 Forbidden |  The password is incorrect
404 Not Found | There's no registration for that app_eui
500 Internal Server Error | Unable to communicate internally for an unknown reason

For all requests below, we consider an `Authorization` header, and the following error codes:

error | source
---|---
400 Bad Request | Wrongly formatted parameter
401 Unauthorized | Wrong or missing Authorization token
404 Not Found | Unable to find the corresponding device / application
500 Internal Server Error | Unable to communicate internally for an unknown reason

**`[GET] /applications/:app_eui/devices`** *+ Authorization*

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)

**`[GET] /applications/:app_eui/devices/:dev_eui`**

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
dev_eui | 8-bytes string hex-encoded | The device identifier (query param)

*Personalized devices' `dev_eui`s are their `dev_addr` prefixed with 4 null-bytes*

**`[PUT] /applications/:app_eui/devices/:dev_eui`**

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
dev_eui | 8-bytes string hex-encoded | The device identifier (query param)
app_key | 16-bytes string hex-encoded | The device AppKey

**`[PUT] /applications/:app_eui/devices/:dev_addr`**

parameter | type | description
---|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
dev_addr | 4-bytes string hex-encoded | The device identifier (query param)
apps_key | 16-bytes string hex-encoded | The device Application Session Key
nwks_key | 16-bytes string hex-encoded | The device Network Session Key

**`[PUT] /applications/:app_eui/devices`**

parameter | type | description
---|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
devices | list of **device_params** | All devices that needs to be registered

> **device_params**
> 
> parameter | type | description
> ---|---|---
> dev_eui | 8-bytes string hex-encoded | The device identifier (query param)
> apps_key | 16-bytes string hex-encoded | The device AppKey
> 
> or
> 
> parameter | type | description
> ---|---|---
> dev_addr | 4-bytes string hex-encoded | The device identifier (query param)
> apps_key | 16-bytes string hex-encoded | The device Application Session Key
> nwks_key | 16-bytes string hex-encoded | The device Network Session Key

**`[DELETE] /applications/:app_eui/devices/:dev_eui`**

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
dev_eui | 8-bytes string hex-encoded | The device identifier (query param)

*Personalized devices' `dev_eui`s are their `dev_addr` prefixed with 4 null-bytes*

**`[DELETE] /applications/:app_eui/devices`**

parameter | type | description
---------------|---|---
app_eui | 8-bytes string hex-encoded | The application identifier (query param)
devices | list of 8-bytes string hex-encoded | The device identifiers

*Personalized devices' `dev_eui`s are their `dev_addr` prefixed with 4 null-bytes*

## Internal RPC communication

Internally, all those requests are transformed to gRPC messages to a handler which will also forward them to its dedicated Broker. Messages will be packed under a same message type the following way:

```proto

enum ManagementAction {
    AUTHENTICATE    = 0;
    READ            = 1;
    UPDATE_ABP      = 2;
    UPDATE_OTAA     = 3;
    DELETE          = 4;
}

message ManagementReq {
    ManagementAction    Action  = 1;
    bytes               AppEUI  = 2;
    oneof Params {
        AuthReq     Auth      = 10;
        ReadReq     Read      = 11;
        UpABPReq    UpABP     = 12;
        UpOTAAReq   UpOTAA    = 13;
        DeleteReq   Delete    = 14;
    }

    message AuthReq {
        string Password = 1;
    }

    message ReadReq {
        string  Token   = 1;
        bytes   DevEUI  = 2; // Nil => Read All
    }

    message UpABPReq {
        string          Token   = 1;
        repeated bytes  DevAddr = 2;
        repeated bytes  NwkSKey = 3;
        repeated bytes  AppSKey = 4;
    }

    message UpOTAAReq {
        string          Token   = 1;
        repeated bytes  DevEUI  = 2;
        repeated bytes  AppKey  = 3;
    }

    message DeleteReq {
        string          Token   = 1;
        repeated bytes  DevEUI  = 2;
    }

}

message ManagementRes {
    ManagementAction    Action  = 1;
    bytes               AppEUI  = 2;
    oneof Params {
        AuthRes      Auth      = 10;
        ReadRes      Read      = 11;
        UpABPRes     UpABP     = 12;
        UpOTAARes    UpOTAA    = 13;
        DeleteRes    Delete    = 14;
    }

    message AuthRes {
        string Token = 1;
    }

    message ReadRes {
        repeated DeviceDescription Devices = 1;
    }

    message UpABPRes {
        repeated DeviceDescription Devices = 1;
    }

    message UpOTAARes {
        repeated DeviceDescription Devices = 1;
    }

    message DeleteRes {}
}

message DeviceDescription {
    bytes DevEUI = 1;
    // More Stuff Later
}

service BrokerOrHandler {
    rpc ManageDevices (ManagementReq) returns (ManagementRes);
}
```

## Remarks

- We don't have to implement all of them initially. We can start by taking care of `[PUT]` requests and `update` actions first as they enable creation and update. 

- Brokers are in charge of generating and verifying Authorization Token. Without a valid Token, the Broker will reject operations from handler.

**Comment by johanstokking** [comment]
Looking into this. Will not use the same message type though.
