### ISSUE TITLE
Contribute to a new Integration

### ISSUE THREAD

**Issue by josmanperez** [TheThingsNetwork/ttn#790]
Hello!, 

I've been working with microprocessors and IoT for some time now but I haven't tried Lora before. I am very new to this world and I would love to contribute while learning.

I sent an email regarding how can I collaborate in creating a new [integration](https://www.thethingsnetwork.org/docs/applications/integrations.html) and they suggested me to write a **question** over the Github repo, so here I am :) 

My idea is to build an integration to connect TTN to [MongoDB Atlas](https://www.mongodb.com/cloud/atlas), I know that currently there is a `Data Storage` integration but I want to also be able to give the community the option to connect through MongoDB and Atlas directly.

I thought about it because MongoDB as a document database could suit most of the projects based on IoT and also because Atlas is a built-in DBaaS with a Free tier option. 

Do you know how can I start? 

Thank you so much,

**Comment by jpmeijers** [comment]
Github isn't the right place for questions like these either. Whoever guided you here was mistaken.

Please ask your question on the Forum:
https://www.thethingsnetwork.org/forum/

Or chat to the other TTN community members over on Slack:
https://thethingsnetwork.slack.com/

**Comment by josmanperez** [comment]
Hello @jpmeijers , thank you for your answer and sorry for asking the question in the wrong place. I've sent an email to ask_us_everything@thethingsnetwork.org and they guided me through here. 

How can I write a comment in the forum? as I don't see an option to do it (sorry if this a silly question)

Regards!
