### ISSUE TITLE
Error fetching device -> Cant delete device from Cluster V2

### ISSUE THREAD

**Issue by elka0711** [TheThingsNetwork/ttn#793]
How to delete the device in V2 ?
Every time when I click to chose the device, the Error fetching device, pop up

**Comment by elka0711** [comment]
![image](https://user-images.githubusercontent.com/34133697/134353502-c637856c-6906-4611-93b0-76c1cd9e3b5d.png)

**Comment by elka0711** [comment]
![image](https://user-images.githubusercontent.com/34133697/134353699-d18c3ff6-d7dd-492c-a8a4-92e40c04ee2f.png)

**Comment by elka0711** [comment]
So it is not possible to bring the sensor up in Cluster V3. 
I believe it is blocked by Cluster V2

**Comment by elka0711** [comment]
![image](https://user-images.githubusercontent.com/34133697/134354086-f6eda823-1d10-43ad-b62c-80ece317f8c9.png)

**Comment by elka0711** [comment]
Fyi,
I am collaborator, with all rights:

- settings
- delete
- devices
- collaborators

**Comment by htdvisser** [comment]
With The Things Network V2 shut down, we're going to archive this repository. This issue will be locked.
