### ISSUE TITLE
DevAddr and Network config should be determined by Broker, not Handler.

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#90]
Broker should allocate `DevAddr` and forward this to the Handler together with the join-request. Handler should use this `DevAddr` to build the join-accept.

Same for (region-specific) network configuration.

**Comment by johanstokking** [comment]
I think this should be implemented in the network controller. We should do this semantically right as we might promote the network controller to a process.

**Comment by htdvisser** [comment]
Yep. I think this network controller should also be responsible for
handling MAC commands, region-specific logic etc.

**Comment by htdvisser** [comment]
@johanstokking: What is our NwkAddr?

**Comment by cambierr** [comment]
Hi @htdvisser !
Is there any updates on this issue ?

**Comment by htdvisser** [comment]
I'm implementing this in the `refactor` branch

**Comment by htdvisser** [comment]
This has been implemented in the `refactor` branch. See #199 for more info.
